### PR TITLE
Adding support for profalux remote MAI-ZTM20C

### PR DESCRIPTION
**Pull request by mauduich**
Adding documentation for MAI-ZTM20C device.

### CODE REVIEW

**Comment by Koenkk** [comment]
Please make the picture a `.jpg`/

**Comment by Koenkk** [comment]
Thanks!

**Comment by mauduich** [comment]
@Koenkk I'm not sure if I did the documentation right.
I followed this procedure https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-add-device-picture-to-zigbee2mqtt-io-documentation
So I cerated a file with only note section. But now when I got to the documentation page there is not all the autogenerated informations. https://www.zigbee2mqtt.io/devices/MAI-ZTM20C.html

I think I'm missing something, but what ?

**Comment by Koenkk** [comment]
The page will be generated with the next z2m release.

**Pull request merged**
