### PR TITLE
Add the white-label version of iolloi ID-EU20FW09

### PR DESCRIPTION
**Pull request by LeoWinterDE**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by pedrolamas** [comment]
@LeoWinterDE can you confirm what does it show for `manufaturerName` on the entry for this device on database.db file?

**Comment by LeoWinterDE** [comment]
@pedrolamas `"manufName":"HZC"` on all 5 that i own.

```
{"id":9,"type":"Router","ieeeAddr":"0x086bd7fffe5d58c4","nwkAddr":1944,"manufId":4714,"manufName":"HZC","powerSource":"Mains (single phase)","modelId":"Dimmer-Switch-ZB3.0","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Dimmer-Switch-ZB3.0","manufacturerName":"HZC","powerSource":1,"zclVersion":3,"appVersion":3,"stackVersion":6,"hwVersion":1,"dateCode":"20200701","swBuildId":"3.09"}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":64}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff06471c","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff06471c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":6,"hwVersion":1,"dateCode":"20200701","swBuildId":"3.09","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-526939472},"lastSeen":1625648706844}
```

**Comment by pedrolamas** [comment]
Confirmed then, I'll change the white-label from Eco-Dim.07 to the new iolloi one.

**Pull request merged**
