### PR TITLE
Update LED1624G9.md

### PR DESCRIPTION
**Pull request by louiecaulfield**
Describes issue regarding minimal brightness when coming from OFF-state

### CODE REVIEW

**Comment by Koenkk** [comment]
does this also happen with other tradfri bulbs?

**Comment by louiecaulfield** [comment]
In the Tradfri series, I only own 2x LED1836G9 and 1x ICPSHC24-30EU-IL-1

They both don't exhibit this behaviour, i.e. when setting the brightness to 1 while they're in an OFF state, they simply turn on at brightness 1.

**Comment by Koenkk** [comment]
Is there no OTA update available for this device? (check the OTA updates tab of the z2m frontend)

**Comment by louiecaulfield** [comment]
> Is there no OTA update available for this device? (check the OTA updates tab of the z2m frontend)

I did - it's running firmware version 2.3.093

**Comment by Koenkk** [comment]
Thanks for checking!

**Pull request merged**
