### PR TITLE
Add Profalux cover and remote images

### PR DESCRIPTION
**Pull request by glamirand**
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3863
https://github.com/Koenkk/zigbee2mqtt/issues/11206

### CODE REVIEW

**Comment by Koenkk** [comment]
- Could you also add the pictures for 1001248 and 1002994?
- Could you rename the cover to `NB102.jpg` and remote to `NSAV061.jpg`?

**Comment by glamirand** [comment]
Sure I will!

**Comment by glamirand** [comment]
> * Could you also add the pictures for 1001248 and 1002994?
> 
>     * Could you rename the cover to `NB102.jpg` and remote to `NSAV061.jpg`?

Here you are!

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
