### PR TITLE
Add a device picture

### PR DESCRIPTION
**Pull request by handy8899**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please use the `model` of the definition as the name, also make it 512x512 and the background transparent.

**Comment by Koenkk** [comment]
- Could you also make a PR to add support for these devices? https://github.com/Koenkk/zigbee-herdsman-converters/pulls
- Please remove `picture.png` from the PR
- The device on `FZT56-ZCW2LBW.png` is quite small, please increase the size of it.

**Comment by handy8899** [comment]
Hello, 
My device is added to Zigbee2MQTT, the function is normal, but it is not supported in the support status,
 whether I can operate Add device picture to zigbee2mqtt.io documentation in Support new devices.
Now that I've added pictures of the FZT56-ZCW2HYH, FZT56-ZCW2LBW models, what do I need to do to make my device display support
谭湖
handy
FAE经理 FAE Manger
Mobile: 15818751880
-------------------------------------------------------------------------------------------------------------------------------------
深圳市飞比电子科技有限公司
Shenzhen Feibit Electronic Technology Co.,Ltd.
深圳市南山区留仙大道3370号南山智园崇文园区2号楼14楼
Addr: 14F, Building 2, Nanshan iPark Chongwen, 3370 Liuxian Avenue, Nanshan District, Shenzhen
Tel：0755-28263320
***@***.*** ***@***.*** > 
www.feibit.com <http://www.feibit.com/ >
--------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------
发件人：Koen Kanters ***@***.***>
发送时间：2024年6月8日(星期六) 23:56
收件人：Koenkk/zigbee2mqtt.io ***@***.***>
抄　送：谭湖 ***@***.***>; Author ***@***.***>
主　题：Re: [Koenkk/zigbee2mqtt.io] Add a device picture (PR #2790)

 * 
Could you also make a PR to add support for these devices? https://github.com/Koenkk/zigbee-herdsman-converters/pulls <https://github.com/Koenkk/zigbee-herdsman-converters/pulls >

 * 
Please remove picture.png from the PR

 * 
The device on FZT56-ZCW2LBW.png is quite small, please increase the size of it.

**Comment by Koenkk** [comment]
See the [docs](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition) on how to support new devices.

**Comment by handy8899** [comment]
Hello, take me what I need to do in order for my device to merge release support

**Comment by handy8899** [comment]
Hello, I have checked that the new version has been released, but my request has not been merged yet. Is there an error in my request? What do I need to do next?
谭湖
handy
FAE经理 FAE Manger
Mobile: 15818751880
-------------------------------------------------------------------------------------------------------------------------------------
深圳市飞比电子科技有限公司
Shenzhen Feibit Electronic Technology Co.,Ltd.
深圳市南山区留仙大道3370号南山智园崇文园区2号楼14楼
Addr: 14F, Building 2, Nanshan iPark Chongwen, 3370 Liuxian Avenue, Nanshan District, Shenzhen
Tel：0755-28263320
***@***.*** ***@***.*** > 
www.feibit.com <http://www.feibit.com/ >
--------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------
发件人：Koen Kanters ***@***.***>
发送时间：2024年6月12日(星期三) 03:07
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Koenkk/zigbee2mqtt.io] Add a device picture (PR #2790)
See the docs <https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition > on how to support new devices.

**Pull request closed without merging**
