### PR TITLE
Fix docker doc

### PR DESCRIPTION
**Pull request by kovacsbalu**
Use network mode `host` as docker-compose

### CODE REVIEW

**Comment by Koenkk** [comment]
Why is this needed?

**Comment by kovacsbalu** [comment]
When you run mqtt broker on your host, not in this container.

**Comment by kovacsbalu** [comment]
Check docker-compose example.

**Comment by kovacsbalu** [comment]
Without this argument i got this logs:
```
zigbee2mqtt:info  2020-02-26 22:44:52: Connecting to MQTT server at mqtt://localhost
zigbee2mqtt:error 2020-02-26 22:45:02: Not connected to MQTT server!
zigbee2mqtt:error 2020-02-26 22:45:12: Not connected to MQTT server!
```
I run mqtt broker in my docker host, not in container. So localhost is not reached from container.

**Comment by Koenkk** [comment]
This is only needed when the MQTT broker runs in a different Docker network than the Zigbee2mqtt container, updated the docs with this information. 

Thanks!

**Pull request merged**
