### PR TITLE
Add Earda - EDM-1ZBA-EU (Smart Dimmer Switch based on Tuya TS0601)

### PR DESCRIPTION
**Pull request by bremme**
I just installed the `Earda - EDM-1ZBA-EU` Smart Dimmer Switch is my house today. At first I thought it was not supported by zigbee2mqtt and so I started to read the documentation on how to add it. But then I found out that it was already added to the `dev` branch. 

There are a couple things to note perhaps. There seems to be some confusion on the model number. Mine has model number: `EDM-1ZBA-EU` (**BA**). But on various other places I see the exact same smart dimmer but with model number `EDM-1ZAB-EU` (**AB**).

For example here:

* https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L1074
* https://zigbee.blakadder.com/Earda_EDM-1ZAB-EU.html
* https://www.alibaba.com/product-detail/EU-Rotary-Button-Light-Wall-Switch_1600076552700.html

This is the one I bought: https://www.aliexpress.com/item/1005001704576003.html and it clearly has `EDM-1ZBA-EU` (**BA**) on the back (I'm looking at it right now:)). I'm not totally sure what going on here? Since I have not seen a picture of the back of a dimmer with the **BA** model number I assume the real model number should be the **AB** one. But I'm not sure?

As of now its probably not possible to get the right picture in the web interface right? All `TS0601_dimmer's` use the same image even though mine has a rotary know instead of touch buttons.

Let me know if you want me to make more changes to the docs. Keep up the good work! I really like this project.

### CODE REVIEW

**Comment by bremme** [comment]
Hmm.. I just found out that I'm not supposed to add the device to `supported_devices.md`. I will undo my changes. How should I solve the issue of mismatching images now?

`TuYa TS0601_dimmer`
image

My `EDM-1ZBA-EU` `TuYa TS0601_dimmer`
image

**Comment by Koenkk** [comment]
I've added the whitelabel in zigbee-herdsman-converters, the documentation is generated based on this.

In this PR the only change should be the addition of the image with the name `EDM-1ZBA-EU.jpg`. (rest will be generated on the next z2m release).

**Comment by bremme** [comment]
Cool. I've removed my original edits and added the `EDM-1ZBA-EU.jpg` image.

**Comment by Koenkk** [comment]
Thanks!

**Comment by bremme** [comment]
You're welcome!

**Pull request merged**
