### PR TITLE
Added picture IKEA Badring

### PR DESCRIPTION
**Pull request by Mettchen**
Added picture to support the IKEA badring

### CODE REVIEW

**Comment by LarsStegman** [comment]
@Koenkk your note to self reminder from https://github.com/Koenkk/zigbee-herdsman-converters/pull/7163 :P

**Comment by Koenkk** [comment]
Could you rename the picture to `E2202.png`?

**Comment by Mettchen** [comment]
> Could you rename the picture to `E2202.png`?

Should be done now, but not 100 % sure :)

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
