### PR TITLE
Add TuYa OTA retrieval guide

### PR DESCRIPTION
**Pull request by Koenkk**
Based on https://gist.github.com/zvldz/2505aa913af185dbdc16a40fbc3303ab

@zvldz could you review this? ([preview](https://github.com/Koenkk/zigbee2mqtt.io/blob/eb59c54427fac55054ba351d3ddace28abfeb602/docs/advanced/more/tuya_ota_url.md))

### CODE REVIEW

**Comment by zvldz** [comment]
looks good

**Comment by zvldz** [comment]
The same method works for Aqara Home

**Comment by zvldz** [comment]
If the device has already been updated. 
It is probably possible to replace the request to make the device look as if it has older firmware.

**Comment by Koenkk** [comment]
> The same method works for Aqara Home

Good to know, thanks for reviewing!

**Comment by zvldz** [comment]
Aqara Home can be mentioned in the instructions )

**Comment by zvldz** [comment]
Works fine on the latest version

**Pull request merged**
