### PR TITLE
Schneider Electric/Clipsal Smoke Alarm 755WSA Image

### PR DESCRIPTION
**Pull request by stevelea**
Schneider Electric/Clipsal Smoke Alarm 755WSA Image

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you make the picture a 512x512 png with transparent background?

**Comment by stevelea** [comment]
Hi,
      Attached , or would u prefer a new pull ?

Regards,
Steve

**Comment by Koenkk** [comment]
I don't see it, can you update this PR?

**Comment by stevelea** [comment]
755WSA
as requested

**Comment by Koenkk** [comment]
Thanks, will add it!

**Pull request closed without merging**
