### PR TITLE
add support for SALUS SPE600

### PR DESCRIPTION
**Pull request by George-andrew**

### CODE REVIEW

**Comment by George-andrew** [comment]
Dear Koenkk, 
I add a photo SPE600 also note for joining device

**Comment by Koenkk** [comment]
The picture and page was already created shows this PR now has a merge conflict. Can you rebase your PR or just refork and reapply changes?

**Comment by George-andrew** [comment]
> The picture and page was already created shows this PR now has a merge conflict. Can you rebase your PR or just refork and reapply changes?

OK, 
I did it,  
currently, done well?

**Comment by Koenkk** [comment]
I still see a lot of unexpected changes in https://github.com/Koenkk/zigbee2mqtt.io/pull/325/files. Could you copy your changes and link to the picture here?

**Pull request closed without merging**
