### PR TITLE
fix: Update and replace Aqara device images

### PR DESCRIPTION
**Pull request by mrskycriper**
This PR is all about cleaning up the mess that is recent png images implementation. A lot of them turned into blobs of color. I've replacing them with the combination of original png froma Aqara web sites, Photoshop background cuts and some images found on the internet.

# Convert

- delete jpgs
- replace corrupted and blurry png
- resize to 512x512

# Backlog

- [x] QBKG11LM QBKG12LM
- [x] QBKG03LM QBKG04LM 
- [x] WXKG02LM
- [x] WXKG03LM
- [x] WXKG04LM
- [x] WXKG05LM
- [x] QBKG17LM QBKG19LM 
- [x] QBKG18LM QBKG20LM
- [x] QBKG33LM QBKG34LM
- [x] WXCJKG11LM
- [x] WXCJKG12LM
- [x] WXCJKG13LM

### H1

- [x] WS-EUK01 WS-EUK03
- [x] WS-EUK02 WS-EUK04
- [x] WXKG14LM
- [x] WXKG15LM WRS-R02
- [x] QBKG27LM
- [x] QBKG29LM QBKG32LM
- [x] ZNXNKG02LM
- [x] ZNQBKG24LM
- [x] ZNQBKG25LM WXKG22LM
- [x] ZNQBKG26LM

### D1

- [x] WXKG06LM
- [x] WXKG07LM
- [x] QBKG21LM QBKG23LM
- [x] QBKG22LM QBKG24LM
- [x] QBKG25LM QBKG26LM

### E1

- [x] WXKG16LM
- [x] WXKG17LM
- [x] QBKG38LM QBKG40LM
- [x] QBKG39LM QBKG41LM
- [x] ZNQBKG31LM

### US

- [x] WS-USC01 WS-USC03
- [x] WS-USC02 WS-USC04

### Buttons

- [x] WXKG11LM WXKG12LM WXKG13LM WXKG20LM

## Sensors

- [x] WSDCGQ11LM WSDCGQ12LM TH-S02D
- [x] RTCGQ11LM RTCGQ12LM RTCGQ15LM
- [x] RTCGQ13LM
- [x] RTCGQ14LM MS-S02
- [x] RTCZCGQ11LM
- [x] SJCGQ11LM SJCGQ12LM WL-S02D SJCGQ13LM
- [x] DJT11LM DJT12LM
- [x] MCCGQ11LM MCCGQ12LM MCCGQ14LM
- [x] VOCKQJK11LM AAQS-S01
- [x] GZCGQ11LM
- [x] JY-GZ-01AQ JY-GZ-03AQ

## Relays

- [x] SSM-U01 DLKZMK11LM
- [x] SSM-U02 DLKZMK12LM
- [x] LLKZMK12LM DCM-K01

## Plugs

- [x] WP-P01D
- [x] ZNCZ12LM
- [x] ZNCZ11LM
- [x] ZNCZ15LM

## Lights

- [x] ZNLDP13LM LEDLBT1-L01
- [x] ZNLDP12LM
- [x] LGYCDD01LM RLS-K01D
- [x] ZNDDMK11LM
- [x] ZNXDD01LM
- [x] XDD11LM
- [x] XDD12LM
- [x] XDD13LM
- [x] ZNTGMK11LM

## Curtains

- [x] ZNCLDJ11LM
- [x] ZNGZDJ11LM SRSC-M01
- [x] ZNGZDJ16LM
- [x] ZNCLBL01LM CM-M01 CM-M01R
- [x] ZNJLBL01LM RSD-M01

## Locks

- [x] ZNMS11LM
- [x] ZNMS13LM

## Other

- [x] MFCZQ12LM CTP-R01
- [x] ZNCWWSQ01LM PETC1-M01

### CODE REVIEW

**Comment by Koenkk** [comment]
Many thanks for this! I know about the `.png` mess, I'm already working on a solution (convert all crappy `.png` from the `.jpg` again using another method)

**Comment by Koenkk** [comment]
Many thanks!

**Comment by hmaiss** [comment]
As of today the icons of my MCCGQ11LM and WSDCGQ11LM do no longer show up in the Z2M web interface. All other icons from non Aqara devices are fine.

**Comment by mrskycriper** [comment]
@hmaiss are your images all jpgs with backgrounds? Because I probably should also re-add jpgs back for compatibility with old web interface

**Comment by hmaiss** [comment]
@mrskycriper Now the Aqara icons are back. When I copy them via Firefox to my local drive I get PNG's without background for all icons (Aqara and other brands).

Thank you!

**Comment by mrskycriper** [comment]
@Koenkk was it ok to delete jpgs? Should I bring them back?

**Comment by Koenkk** [comment]
@mrskycriper ah I missed this indeed, please put back the `.jpg` files (they are still used in older z2m releases)

**Comment by mrskycriper** [comment]
@Koenkk got it, thankfully I have all the  high rez files on hand so it will be faster this time

**Comment by Koenkk** [comment]
@mrskycriper don't spend too much time on it, just putting the old 150x150 `.jpg` back is sufficient

**Pull request merged**
