### PR TITLE
[WIP] Move device configuration to devices page

### PR DESCRIPTION
**Pull request by sjorge**
- [ ] `npm run docgen` generates changes on master, move those to the proper location.
- [ ] Add 'Device specific configuration' section to 'notes' section for all devices.
- [ ] Move device configuration to per-device page from MQTT Topics and message structure page

### CODE REVIEW

**Comment by sjorge** [comment]
Yeah that was a wasted efford :( will revist this because I totally overlooked the docgen dir.

**Comment by sjorge** [comment]
OK I started from scratch and after a checkout of master imediatly ran `npm run docgen` and there are a bunch of diffs.

I will have to get these in the correct location first it seems.

**Comment by Koenkk** [comment]
Yes, it is greatly out of sync atm, I will try to bring it in sync (as it needs to be prepped for zigbee2mqtt 1.7)

**Comment by sjorge** [comment]
> Yes, it is greatly out of sync atm, I will try to bring it in sync (as it needs to be prepped for zigbee2mqtt 1.7)

How flexible is docgen? Can we add a dict of 'device configuration' ?

Something like 
```
{
 'some_key': 'set some config to some value, range 0-255',
 'other_key': 'set some other thing, values on or off',
}
```

And have it auto generate the section?

**Comment by Koenkk** [comment]
As flexible as we can make it, but first I need to update the docgen because currently it  is a mess.

**Pull request closed without merging**
