### PR TITLE
Create MLI-404051.png & Update correct LED2109G6.png

### PR DESCRIPTION
**Pull request by Chrischan-git**
Please add picture MLI-404051.png for support new device.

The image for the LED2109G6 was not the correct one. So please change to this one.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you make the background transparent? Use e.g. https://www.adobe.com/express/feature/image/remove-background

**Comment by Chrischan-git** [comment]
Sorry, thought it was transparent.
Can I upload it right here?

MLI-404051



LED2109G6

**Comment by Koenkk** [comment]
Could you update this PR? I think you can do it by uploading files [here](https://github.com/Chrischan-git/zigbee2mqtt.io/tree/master/public/images/devices)

**Comment by Chrischan-git** [comment]
Done.
Sorry, was my fist PR ;-)
Thanks!

**Pull request merged**
