### PR TITLE
About cc2538 adapter

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by Koenkk** [comment]
Before making this an official supported adapter, the source code should be in https://github.com/koenkk/z-stack-firmware

**Comment by kirovilya** [comment]
ok :) https://github.com/Koenkk/Z-Stack-firmware/pull/144

**Comment by Koenkk** [comment]
good, I think the following things are missing before it can be used by the community:

- Instructions how to make the dongle
- Instructions how to flash the dongle

**Comment by kirovilya** [comment]
These instructions are in issue and links there, like this https://modkam.ru/?p=1112 (but in russian).
there are also ready-made devices, links are exists in description

**Comment by Koenkk** [comment]
Could it be translated to English? Otherwise it's not very useful for the zigbee2mqtt docs.

**Comment by kirovilya** [comment]
I will try to translate. but now you can translate it with a browser too :) 
If you look at the issue, then some have already made them yourself

**Comment by Gamester17** [comment]
Does the README.md for Z-Stack-firmware coordinator firmware also need to be updated for now that #144 have been merged adding support for CC2538 + CC2592 module?

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/README.md

**Pull request closed without merging**
