### PR TITLE
Lidl-alt-models

### PR DESCRIPTION
**Pull request by Chartreusito**
Add newer models already supported as white-label alts. Models from 2022-02 and 2022-07 as stated on product packaging.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of these devices?

**Comment by Chartreusito** [comment]
I must admit it took a bit of time to understand what you meant by database entry, i'm not used to get into this file :D
I can't provide entry for every devices cause i extrapolated a bit. For each "generation" (or should i say batch ?), Lidl sells GU10 (suffix A), E14 (suffix B) and E27 (suffix C), as you can see here : https://www.bruksanvisni.ng/livarno/hg09155a/bruksanvisning?p=7
Those generations are either CCT or RGB for now.
I've got devices from generation HG09155 (RGB), HG09154 (CCT) and HG08130 (CCT). I must admit i mostly took the last revisions that were available, but it's kind of random Lidl wise. I did not see any difference on functionnality yet.
Here are entries for devices i own :
HG08130A : 
{"id":108,"type":"Router","ieeeAddr":"0x540f57fffe78a020","nwkAddr":8195,"manufId":4098,"manufName":"_TZ3000_el5kt5im","powerSource":"Mains (single phase)","modelId":"TS0502A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0502A","manufacturerName":"_TZ3000_el5kt5im","powerSource":1,"zclVersion":3,"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1689275732162,"defaultSendRequestWhen":"immediate"}
HG08130C : 
{"id":106,"type":"Router","ieeeAddr":"0x9035eafffed1b51e","nwkAddr":50724,"manufId":4098,"manufName":"_TZ3000_49qchf10","powerSource":"Mains (single phase)","modelId":"TS0502A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0502A","manufacturerName":"_TZ3000_49qchf10","powerSource":1,"zclVersion":3,"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1689252867237,"defaultSendRequestWhen":"immediate"}
HG09154C :
{"id":105,"type":"Router","ieeeAddr":"0x003c84fffed6e97c","nwkAddr":26821,"manufId":4098,"manufName":"_TZ3000_49qchf10","powerSource":"Mains (single phase)","modelId":"TS0502A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0502A","manufacturerName":"_TZ3000_49qchf10","powerSource":1,"zclVersion":3,"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1689252301893,"defaultSendRequestWhen":"immediate"}
HG09155A :
{"id":103,"type":"Router","ieeeAddr":"0x540f57fffe37bb87","nwkAddr":11158,"manufId":4098,"manufName":"_TZ3000_quqaeew6","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3000_quqaeew6","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":29}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1689258367165,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
I see they are re-using the manufacturerName. I've updated the model to include those, e.g. `_TZ3000_el5kt5im` = `HG06492A` is now  `HG06492A/HG08130A`.

The docs will be automatically regenerated with the next release (it will rename the .md files instead of adding them as whitelabel)

**Comment by Chartreusito** [comment]
Thank you !

**Pull request closed without merging**
