### PR TITLE
Update image for zigbee2mqtt 1.36.1 release

### PR DESCRIPTION
**Pull request by xrust83**
Update image png 512x512

This release adds support for 38 devices zigbee2mqtt 1.36.1 release (@Koenkk, @nurikk)

`929003621301` Philips Hue White & Color ambience Centris ceiling light (4 spots) (black) (@thk-socal)
`EFEKTA_iAQ3` EFEKTA CO2 Monitor with IPS TFT Display, outdoor temperature and humidity, date and time (@kirovilya)
`WS-K01D` Aqara Smart 20A Switch H1 (single rocker) (@TzeWey)
`CTM_MBD_Dim` CTM Lyng MBD Dim, motion detector with dimmer (@soversk)
`ZG-204ZM` TuYa PIR 24Ghz human presence sensor (@13717033460)
`442296118491` Philips Hue Secure Camera Floodlight (@JohnConnett)
`THPZ1` Tapestry Presence sensor Z1 occupancy and temperature/humidity sensor (@taby1)
`LED2111G6` IKEA TRADFRI LED bulb E14 806 lumen (@leoshusar)
`SLZB-06M` SMLIGHT Router (@Koenkk)
`DIO-300Z` ShinaSystem SiHAS DI/DO Module (@shinasys)
`L2206` IKEA JETSTRÖM LED wall light panel, smart dimmable/wired-in colour and white spectrum, 30x30cm (@jamesonuk)
`99106` EGLO Connect-Z motion (PIR) sensor (@Johannest85)
`CK-BL702-ROUTER-01(7018)` eWeLink USB router (@Koenkk)
`Nimly` Onesti Products AS Zigbee module for Nimly Doorlock series (@newlund)
`SWV` SONOFF Zigbee smart water valve (@lukezxm)
`MEG5126-0300/MEG5172-0000` Schneider Electric Merten MEG5172 PlusLink Dimmer insert with Merten Wiser System M Push Button (2fold) (@Nailik)
`07767L` Immax NEO Smart outdoor button (@Tezar)
`HCXDD12LM` Aqara Ceiling light T1 (@banister4728)
`CL-L02D` Aqara Ceiling light T1M (@banister4728)
`SR-ZS` Moes Smart switch (light + sence) (@kirovilya)
`LED2109G6` IKEA TRADFRI LED bulb E27 806 lumen, dimmable, color, opal white (@millionsofjeffries)
`TS0601_gas_sensor_3` TuYa Gas sensor (@onmobs)
`929002401101` Philips Hue Iris silver limited edition (generation 4) (@folta)
`SPM02-U01` BITUO TECHNIK Smart energy sensor (@script0803)
`ZP1-EN` IMOU Zigbee ZP1 PIR motion sensor (@array81)
`ZR1-EN` IMOU Zigbee ZR1 siren (@array81)
`E2202` IKEA Water leakage detection sensor (@Mettchen)
`ZNQBKG42LM` Aqara Smart wall switch Z1 Pro (single rocker) (@mrskycriper)
`ZNQBKG43LM` Aqara Smart wall switch Z1 Pro (double rocker) (@mrskycriper)
`ZNQBKG44LM` Aqara Smart wall switch Z1 Pro (triple rocker) (@mrskycriper)
`ZNQBKG45LM` Aqara Smart wall switch Z1 Pro (quadruple rocker) (@mrskycriper)
`Icon2` Danfoss Icon2 Main Controller, Room Thermostat or Sensor (@TautrimasM)
`OSL 132 C` Innr Outdoor smart spot color (@philmtd)
`EA4161C-BI` TuYa Single-phase multifunction energy meter (DIN Module) (@SKDS)
`TRZB3` Third Reality Roller blind motor (@skosyi)
`929003531502` Philips Hue white ambiance ceiling white Enrave M with Bluetooth (@galligan)
`ZB-3008` RGB Genie 3 scene remote and dimmer (@ejpenney)
`CK-BL702-AL-01` TuYa Zigbee LED bulb (@Koenkk)

### CODE REVIEW

**Comment by mrskycriper** [comment]
Aren't almost all of them already present? What's the point of this PR?

**Comment by Nailik** [comment]
@mrskycriper probably adding more features to the devices. Eg the Merten devices I changed now supports changing the switchActions and the code is updated to use modernExtend

**Comment by mrskycriper** [comment]
> @mrskycriper probably adding more features to the devices. Eg the Merten devices I changed now supports changing the switchActions and the code is updated to use modernExtend

I see only slight changes is some pictures. And no changes in others. That's why I'm asking. 

Also I probably wouldn't have seen this PR without that tag, so there's also curiosity at play :)

**Comment by mrskycriper** [comment]
> So the changes are only in the photo of the devices. If so, please teach me. It's just that I started making a new base of pictures a long time ago

I'm mostly interested in changes like this. Where seemingly nothing is happening.

image

**Comment by mrskycriper** [comment]
> I take the list of pictures from the latest update. I download them from the zigbee2mqtt database. If the picture meets the requirements, I do not touch it, if the picture is small or of poor quality, I find and crop a new one. I did it in a batch, and then filled all the pictures again. It takes less time than going back and forth to see which picture was good and which one I replaced. There is a problem with this that the picture was overwritten, I think I did not harm it. In any case, please help, explain and teach.

Ah, I see, that makes sense now. Thanks!

**Comment by Nailik** [comment]
> > @mrskycriper probably adding more features to the devices. Eg the Merten devices I changed now supports changing the switchActions and the code is updated to use modernExtend
> 
> I see only slight changes is some pictures. And no changes in others. That's why I'm asking.
> 
> Also I probably wouldn't have seen this PR without that tag, so there's also curiosity at play :)

ahh i see sorry, i was just on the phone and didn't see everything correctly sorry.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
