### PR TITLE
Docs - Add MQTT broker requirement in getting started guide

### PR DESCRIPTION
**Pull request by teameh**
I'm an absolute beginner. It was not clear to me I had to make sure a broker was running until I figured this out from the logs.

### CODE REVIEW

**Comment by teameh** [comment]
See also https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/246/files

**Comment by teameh** [comment]
Would it also make sense to add it to the "Zigbee2MQTT fails to start" FAQ? In my case it wouldn't start because I had no broker running.

**Comment by Koenkk** [comment]
This is fine, thanks!

**Comment by teameh** [comment]
\0/ thanks for the quick reply!

**Pull request merged**
