### PR TITLE
Add Aurora bulb model AU-A1GSZ9B/27

### PR DESCRIPTION
**Pull request by nez-nix**

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you remove the logo from the picture? Without looks nicer.

**Comment by nez-nix** [comment]
> Could you remove the logo from the picture? Without looks nicer.

Sure. That thought actually crossed my mind last night and I'd considered it. I've a couple of things to do but I will change the picture today.

**Comment by nez-nix** [comment]
OK. I've changed the picture so that there's no silly logo in the corner.

How does the automation know how to match my new picture up with the other PR that I added to zigbee-herdsman-converters repo?
Does it just grep for a correlation, or is it something you have to do a quick manual check for?

I tried spelling them as clearly as possible but there is a slash in the model name ('AU-A1GSZ9B/27'), which complicates things.

Just curious.

**Comment by Koenkk** [comment]
> I tried spelling them as clearly as possible but there is a slash in the model name ('AU-A1GSZ9B/27'), which complicates things.

The file name should be  `AU-A1GSZ9B-27.jpg`

**Comment by nez-nix** [comment]
> > I tried spelling them as clearly as possible but there is a slash in the model name ('AU-A1GSZ9B/27'), which complicates things.
> 
> The file name should be `AU-A1GSZ9B-27.jpg`

Done.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
