### PR TITLE
Add docs about reporting and optimistic mode

### PR DESCRIPTION
**Pull request by trapacska**

### CODE REVIEW

**Comment by trapacska** [comment]
@Koenkk it took me days to research this info and I found it a must have for the ones like me(migrating from ZHA to Z2M) because these configurations are required if I want to achieve the very same experience in Z2M as I originally had with ZHA.

**Comment by Koenkk** [comment]
Can you merge this to the already existing docs?

- https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-device-configure-reporting
- https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#common-device-options

**Comment by trapacska** [comment]
Sure! I am sad I did not find the already existing! Going to update soon.

**Comment by trapacska** [comment]
@Koenkk merged

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
