### PR TITLE
Add EGLO lamp to 33951_33948.md

### PR DESCRIPTION
**Pull request by elporsche**
Update to include the EGLO ledfilamentlamp Zigbee G95 dimbaar warm E27 6W as an additional product supported with the same hardware name. Note: I tried to add the picture as per the instructions on https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device, but the target site (https://www.zigbee2mqtt.io/public/images/devices/) throws me an Error 404. For now, I linked the vendor's website (that contains a picture).

### CODE REVIEW

**Comment by Koenkk** [comment]
Is your EGLO 12229 detected as a Awox 33951/33948?

**Comment by elporsche** [comment]
> Is your EGLO 12229 detected as a Awox 33951/33948?

Yes

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of this device?

**Comment by elporsche** [comment]
> Could you provide the data/database.db entry of this device?

do you mean this one (got it from /opt/zigbee2mqtt/data/database.db):
 
{"id":3,"type":"Router","ieeeAddr":"0xa4c1388906e183d9","nwkAddr":49300,"manufId":4417,"manufName":"AwoX","powerSource":"Mains (single phase)","modelId":"TLSR82xx","epList":[1,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,768,4096,64599],"outClusterList":[6],"clusters":{"genBasic":{"attributes":{"appVersion":0,"hwVersion":0}},"lightingColorCtrl":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":4751,"epId":3,"devId":257,"inClusterList":[65360,65361],"outClusterList":[65360,65361],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1651851265298,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
This device definitely falls into the white-label category, as you can see the device uses the AwoX manufacturer name (`"manufName":"AwoX"`). I've added them as such now, meaning they will appear as a separate device on the supported devices list and will be added to the whitelabel row of the AwoX device page (example: https://www.zigbee2mqtt.io/devices/AV2010_22.html). This will be updated automatically with the next release (since this part of the doc is generated). Same applies to https://github.com/Koenkk/zigbee2mqtt.io/pull/1369

**Pull request closed without merging**
