### PR TITLE
adding an Image for TS0501A

### PR DESCRIPTION
**Pull request by Jimmypl007**
As I mentioned when I added my "definition" to the tuya.js file in zigbee-herdsman-converters/devices Despite my research i really have no idea what i am doing..
I know that there's a possibility that there will be more TS0501A's so i don't know the naming convention i should use as it didn't mention it for Tuya devices in the tutorial. but as it seems i am the first i'm just going to call it TS0501A.jpg. As for the .md folder, apart from basic details available in the "definition"  I wouldn't know where to begin on creating one. I tried opening one that I downloaded and it told me not to edit anything outside "note". also the tutorial said it was optional? i figured you would need an image though so here ya go..

sorry again if i am doing things wrong.

### CODE REVIEW

**Comment by Koenkk** [comment]
I forgot to merge this, but meanwhile the pr got in a conflict, could you recreate the mr so I can merge it?

**Comment by Jimmypl007** [comment]
> I forgot to merge this, but meanwhile the pr got in a conflict, could you recreate the mr so I can merge it?

No problem, I'll do this when I get home from work today. 
Thanks again for your help.

**Comment by Jimmypl007** [comment]
that's done, its #1210

**Comment by Koenkk** [comment]
thanks!

**Pull request closed without merging**
