### PR TITLE
Add WZ-M100-Z a new device

### PR DESCRIPTION
**Pull request by SmartHomeThingy**
Picture and page was missing so I've added it.
Device is simmilar / equal to WZ-M100-W.
The recently added external converter for the WZ-M100-W is working for the WZ-M100-Z too, so no further modification required as it currently looks like.

This is my first ever pull. Let me know if something is not ok and I'll fix it

### CODE REVIEW

**Comment by Koenkk** [comment]
Hey! In order to have a device page, the device also needs to be added to https://github.com/koenkk/zigbee-herdsman-converters

**Comment by SmartHomeThingy** [comment]
> Hey! In order to have a device page, the device also needs to be added to https://github.com/koenkk/zigbee-herdsman-converters

I'm not 100% sure what to do there. The Device is a Tuya compatible device just like the WZ-M100-W and I did not find any page for this device . Can you point me to what I need to do ?
I've created the WZ-M100-Z.md here, thought that's it ;)

**Comment by Koenkk** [comment]
How is the device currently recognised when pairing with z2m?

**Comment by SmartHomeThingy** [comment]
> How is the device currently recognised when pairing with z2m?

grafik

grafik

**Comment by Koenkk** [comment]
`WZ-M100-Z` is not a supported device, do you have an external converter in your `configuration.yaml`?

**Comment by SmartHomeThingy** [comment]
I must say I had, but right now it's empty
grafik

I used these converters the vendor provided me.
https://github.com/wzwenzhi/Wenzhi-ZigBee2mqtt/blob/main/README.md
Both files are next to the configuration.yaml but that's it.

**Comment by Koenkk** [comment]
Can you make a screenshot of the z2m frontend -> settings -> about tab?

**Comment by SmartHomeThingy** [comment]
grafik


grafik

**Comment by SmartHomeThingy** [comment]
Let me know if you ned any more info

**Comment by Koenkk** [comment]
In the next release (1 December), this will be detected as a `WZ-M100-W`.

**Comment by SmartHomeThingy** [comment]
So it was incorrectly found then ? Shall I close the Request then ?

**Comment by Koenkk** [comment]
Yes, I will close it, let me know if it is not correctly regonised after updating to the 1 December release, then we can re-open this.

**Comment by SmartHomeThingy** [comment]
thanks. will do

**Comment by SmartHomeThingy** [comment]
Hi @Koenkk , I tried adding the device back in but it is still recognized as WZ-M100-Z.

I removed the 2 additional files and confirmed that in my config there are no external convertors in my configuration still.

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by SmartHomeThingy** [comment]
Hmmm, not sure what is different today, but it's now recognized correctly.

**Pull request closed without merging**
