### PR TITLE
Update deconz adapter information

### PR DESCRIPTION
**Pull request by hhromic**
* Mention ConBee and RaspBee as they are also supported.
  * Source: I own a RaspBee and works perfectly with Zigbee2MQTT.
* Update firmware link, buying links and general wording.

Note: While I don't own a ConBee, it uses the same chipset as the RaspBee and therefore it _should_ also be compatible.

### CODE REVIEW

**Comment by Koenkk** [comment]
@chrishae can you confirm the first version of the raspbee and conbee are also supported?

**Comment by hhromic** [comment]
@Koenkk for what is worth, zigbee2mqtt actually reports my RaspBee as both "ConBee/RaspBee" :)

image

**Comment by ChrisHae** [comment]
ConBee (1) and RaspBee (1) are also supported. They use the same chip. And the firmware version which they expose to zigbee2mqtt has the same byte for that chip. So they can't be distinguished by the firmware version.

**Comment by Koenkk** [comment]
Thanks guys! 👍

**Pull request merged**
