### PR TITLE
Update R7051.md

### PR DESCRIPTION
**Pull request by elninosi**
Correcting topic to publish payload.

### CODE REVIEW

**Comment by Koenkk** [comment]
I don't see how this could work, `set_message` is not part of the Z2M api. Could you explain this further?

**Comment by elninosi** [comment]
It did not work with "set" payload. After a few more digging I found out it is working with "set_message", here is log example:
slika

**Comment by Koenkk** [comment]
Can you provide the debug log when using `/set`?

**Comment by Koenkk** [comment]
Could you provide the herdsman debug log of both `set` and `set_message`?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Pull request closed without merging**
