### PR TITLE
Image for Tuya TS0601 TZE204_81yrt3lo #18419

### PR DESCRIPTION
**Pull request by dams74**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please rename the picture to `PJ-1203A.jpg`

**Comment by Koenkk** [comment]
Please use `.jpg` only once, it's `.jpg.jpg` now.

**Review by dams74 — COMMENTED** [review]
The name of picture is ok now

**Review by dams74 — COMMENTED** [review]
Sorry for the bad name
It's ok now

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
