### PR TITLE
Add images for TS0041A

### PR DESCRIPTION
**Pull request by mhosse**
This adds images for the wireless switch with 1 button TS0041A

### CODE REVIEW

**Comment by Koenkk** [comment]
Please make the background transparent.

**Comment by mhosse** [comment]
@Koenkk PNG has transparent background, JPG of course not.

**Comment by Koenkk** [comment]
The jpg is not needed anymore, could you rename the png to `Push_ME.png`?

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
