### PR TITLE
Add Silicon Labs EZSP as experimental to supported adapters list

### PR DESCRIPTION
**Pull request by Hedda**
Added Silicon Labs EZSP v8 on EFR32 with 6.7.8 FW to supported adapters list as "**_experimental_**" and "_**pre-alpha stage**_" to website.

https://www.zigbee2mqtt.io/information/supported_adapters.html

<div style="width: 1000px">
<table>
  <tr>
    <td><b>Picture</b></td>
    <td><b>Name</b></td>
    <td><b>Description</b></td>
    <td><b>Firmware</b></td>
    <td><b>Guides</b></td>
    <td><b>Buy</b></td>
  </tr>
  <tr>
    <td></td>
    <td>Silicon Labs EZSP v8 <b>(experimental)</b></td>
    <td>Initial development started on experimental (pre-alpha stage) support for various adapters based on Silicon Labs EFR32 SoC families with EmberZNet NCP 6.7.8 firmware or later via EZSP version 8 (EmberZNet Serial Protocol) interface. This include all hardware based on SoCs/Modules from Silabs EFR32MG21/MGM210 and EFR32MG12/MGM12 series.</td>
    <td><a href="https://github.com/Koenkk/zigbee-herdsman/issues/319">Coordinator</a><br/></td>
    <td></td>
    <td></td>
  </tr>
</table>
</div>

### _Notes_
- _Support for the **Conbee II** ([discussion](https://github.com/Koenkk/zigbee-herdsman/issues/72)), **ZiGate USB-TTL** ([discussion](https://github.com/Koenkk/zigbee-herdsman/issues/242)), and **Silicon Labs EZSP** ([discussion](https://github.com/Koenkk/zigbee-herdsman/issues/319)) is experimental, meaning not feature complete nor recommended for a stable enviroment._

## References:

https://github.com/Koenkk/zigbee-herdsman/issues/319

https://github.com/Koenkk/zigbee-herdsman/pull/317

https://github.com/Koenkk/zigbee2mqtt/pull/6532

### CODE REVIEW

**Comment by Koenkk** [comment]
I'm not sure if it should be added already, @kirovilya mentioned it's in the alpha stage currently

**Comment by Hedda** [comment]
> I'm not sure if it should be added already, @kirovilya mentioned it's in the alpha stage currently

OK. Maybe change PR to draft? ...I just thought the comment about it being "experimental" equals "alpha" as well as "beta"(?).

**Comment by Hedda** [comment]
@kirovilya Maybe EZSP support in Z2M could be listed as "pre-alpha"? https://en.wikipedia.org/wiki/Software_release_life_cycle

image

**Comment by kirovilya** [comment]
:) I didn't have such global plans.
I thought that alpha is when the basic functionality works and you can try to use it.

then, when the main functionality is implemented and it will be possible to offer to use it on an ongoing basis, there will be a beta.

a release can be considered the execution of all scheduled tasks.

**Comment by Hedda** [comment]
FYI, EZSP adapter should work with all of these once have updated to Silicon Labs EmberZNet 6.7.x coordinator firmware or later:

- Zigbee 3.0 dongle from ITead (coming soon?) https://community.home-assistant.io/t/zigbee-3-0-usb-dongle-from-itead-based-on-silicon-labs-efr32mg21-soc/271144
- Elelabs Zigbee USB Adapter (ELU013) https://elelabs.com/products/elelabs-usb-adapter.html
- Elelabs Zigbee Raspberry Pi Shield (ELR023) https://elelabs.com/products/elelabs-zigbee-shield.html
- Defaro Sprut stick https://spruthub.ru/device/defaro-sprut-stick-2-pro (description in Russian, use a translator)
- EByte E180-ZG120B dev board if reflashed [zigpy/zigpy#584](https://github.com/zigpy/zigpy/discussions/584)
- Flashed USB stick based on SM-011 https://modkam.ru/?p=1889 (description in Russian, use a translator)
-  TubesZB style ESP8266/ESP32 based DIY Zigbee to Ethernet gateways running ESPHome with serial-bridge configuration, see https://github.com/tube0013/tube_gateways and https://github.com/zigpy/zigpy/discussions/584 and https://www.tubeszb.com/shop/coordinators/2
- Tuya TYGWZ01 / Lidl / Silvercrest Smart Gateway hacked with DIY firmware https://github.com/zigpy/zigpy/discussions/650
- DIY "Billy EZSP" using IKEA TRÅDFRI ICC-A-1 Module ripped from an IKEA Tradfri Series device with hacked firmware https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Module
- Sonoff ZBBridge Zigbee WiFi Bridge gateway re-flashed with Tasmota (though it not recommended since the WiFi connection does not make for a stable solution) https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html
- Nortek GoControl QuickStick Combo Model HUSBZB-1 (note that this is based on Silabs older EM3581 "Ember" family chip)
- Telegesis ETRX357USB if reflashed (note that this is based on even older Silabs EM357 / EM357x "Ember" family chip)

USB-stick firmware can be updated with Elelabs EZSP Firmware Update Utility or the Zigbee firmware updater image by walthowd

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility

https://github.com/walthowd/husbzb-firmware

https://github.com/zha-ng/EZSP-Firmware

https://github.com/grobasoz/zigbee-firmware/

Direct link to zigpy wiki page where MattWestb documented recommended application firmware version for EZSP Coordinators:

https://github.com/zigpy/zigpy/wiki/Coordinator-Firmware-Updates#recommended-firmware-version-for-ezsp-coordinators

**Comment by Hedda** [comment]
> FYI, EZSP adapter should work with all of these once have updated to Silicon Labs EmberZNet 6.7.x coordinator firmware or later:
> 
> * Zigbee 3.0 dongle from ITead (coming soon?) https://community.home-assistant.io/t/zigbee-3-0-usb-dongle-from-itead-based-on-silicon-labs-efr32mg21-soc/271144


FYI, the mentioned inexpensive yet powerful Zigbee 3.0 USB dongle from ITead is now available for $6.99 (US) directly from China:

https://www.itead.cc/zigbee-3-0-usb-dongle.html

Limited first production run and Silabs now has delayed parts so maybe not get greedy and perhaps let developers order first(?).

**Review by Zidane115 — COMMENTED** [review]
**wewe**

**Comment by Hedda** [comment]
> **wewe**

Are you a bot? You should not review pull requests that where merged and closed 3-years ago!

**Pull request merged**
