### PR TITLE
Add image for Paul Neuhaus Q-PLUG Adapter Plug

### PR DESCRIPTION
**Pull request by kpdroiddev**
Please merge this pull request together with [the code changes](https://github.com/Koenkk/zigbee-shepherd-converters/pull/427)

Make the newly added Paul Neuhaus Q-PLUG appear in the list of supported devices

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by kpdroiddev** [comment]
Hey, tnx for the merge :)
Will you run the docgen? I am not sure how to do, I always get the message 
`internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'zigbee2mqtt/node_modules/zigbee-shepherd-converters'`
Cheers

**Comment by Koenkk** [comment]
I will do this on the next zigbee2mqtt release (1.4)

**Comment by kpdroiddev** [comment]
Perfect 👍

**Pull request merged**
