### PR TITLE
Added some extra information on how to get your USB device Virtual COM port visible inside flashing software

### PR DESCRIPTION
**Pull request by hvanmegen**
# Added some extra information on how to get your USB device Virtual COM port visible on an OS such as Windows

It took me a couple of hours to figure out that none of my Windows 10 machines had any drivers installed to communicate with the virtual com port over USB, luckily the discord community put me on the right path, hence my effort here to try to alleviate this problem for anyone else with the same problem.

Also incorporated sentence / question with possible search query into the explanation to maximize SEO

I also rendered a PDF from the sonoff's website's .docx document, since not everyone has access to MS-Word.

I hope this helps someone!

### CODE REVIEW

**Comment by hvanmegen** [comment]
that pull request on my own repository was me being a bit rusty with GitHub.. it's been years since I've created a pull request 🤣

**Comment by hvanmegen** [comment]
hopefully the path will work now.. (sorry for me not checking this earlier)

**Comment by hvanmegen** [comment]
sigh.. full path to the original repository.. dno if it will work, but I don't want to link to the document in my repository to prevent all kinds of convoluted nonsense

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
