### PR TITLE
initial PR for TOQCB2-80 from TONGUE

### PR DESCRIPTION
**Pull request by bifi2090**

### CODE REVIEW

**Review by bifi2090 — COMMENTED** [review]
Add template for notes

**Comment by Koenkk** [comment]
Could you fix the casing of the picture (should be `TOQCB2-80.png`), you may have to remove, commit and add and commit to make Git detect the changes.

**Comment by bifi2090** [comment]
> Could you fix the casing of the picture (should be `TOQCB2-80.png`), you may have to remove, commit and add and commit to make Git detect the changes.

Check😄

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
