### PR TITLE
Update InstaRemote Device Page

### PR DESCRIPTION
**Pull request by felixstorm**
Add information:
* solving problems loosing network connection
* how to factory reset
* how to join a network
* how to prepare for OTA updates.

Also updates description and white label devices in accordance with https://github.com/Koenkk/zigbee-herdsman-converters/pull/1660

Thanks,  
Felix

### CODE REVIEW

**Comment by felixstorm** [comment]
I just saw that the checks have failed due to the additional images included to demonstrate factory reset and network join procedures.  
I will be happy to move them to a better location if you have a hint where to put them (or feel free to move them yourself).

Thanks,  
Felix

**Comment by Koenkk** [comment]
Thanks, can you move the images one directory up? https://github.com/Koenkk/zigbee2mqtt.io/tree/5b972099f332c6f48e79870a5c5b894bf304053d/docs/images . Otherwise tests will fail.

**Comment by felixstorm** [comment]
sorry - will fix the image in a few minutes...

**Comment by felixstorm** [comment]
@Koenkk the checks seem to look better now 😉

**Comment by Koenkk** [comment]
Perfect, thanks!

**Pull request merged**
