### PR TITLE
Add detail-summary styles; refactor supported adapters

### PR DESCRIPTION
**Pull request by psi-4ward**
image

### CODE REVIEW

**Comment by Koenkk** [comment]
Awesome!

I found one issue, now it looks that the conbee is based on a TI chip:

image

**Comment by psi-4ward** [comment]
> Awesome!
> 
> I found one issue, now it looks that the conbee is based on a TI chip:
> 
> image

Ups, fixes
https://github.com/Koenkk/zigbee2mqtt.io/blob/25ae98af77f1288f788d512aec141564937eda7b/docs/guide/adapters/README.md

**Comment by psi-4ward** [comment]
PS: feel free to fix little typos like that yourself :-)

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
