### PR TITLE
CCT711119: Add pairing guidance

### PR DESCRIPTION
**Pull request by samip5**
Was quite difficult to find as it's only on the original piece of paper that came with it.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by samip5** [comment]
It seems that the pairing image doesn't show up? @Koenkk

**Comment by Koenkk** [comment]
Fixed!

**Comment by samip5** [comment]
Doesn't appear to? https://www.zigbee2mqtt.io/devices/CCT711119.html

**Comment by Koenkk** [comment]
Whoops, I pushed to the wrong branch, fixed now.

**Pull request merged**
