### PR TITLE
_TZE204_ztqnh5cg image

### PR DESCRIPTION
**Pull request by Nikpesu**
missed image

### CODE REVIEW

**Comment by Koenkk** [comment]
Do you know what model number is written on the device itself or product page?

**Comment by Nikpesu** [comment]
24G Zigbee/WiFi Human Presence Sensor Smart Human Body PIR Sensor Detector Motion Sensors Work With Alexa Google Home 

Description:
Communication Mode： WiFi Zigbee 3.0
Type: **`ZN509546`**
Working Temperature：-10°C~55°C
Detection Angle：>90°
Transmission Frequency：5.8G rado 24G rado
Working Voltage：DC5V 1A
Sensitivity：0-10

https://www.aliexpress.com/item/1005006411569364.html

**Comment by Koenkk** [comment]
Then please rename the picture to `ZN509546.png`

**Comment by Burki24** [comment]
This Sensor is an 'iHseno', 'TY_24G_Sensor_V2', 'Human presence sensor', ['_TZE204_ztqnh5cg'. I fixed it in tuya.ts and add picture to it.

**Pull request closed without merging**
