### PR TITLE
new devices

### PR DESCRIPTION
**Pull request by blackcult**
Added new devices in https://github.com/Koenkk/zigbee-herdsman-converters/pull/5341

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by jdrozdnovak** [comment]
Hello! @Koenkk . How are you planning to build the new images when the OpenSource docker hub is being purged? Is there a way to support your project?

**Comment by Koenkk** [comment]
I'm not aware of this, can you link me an article?

**Comment by jdrozdnovak** [comment]
> I'm not aware of this, can you link me an article?

https://blog.alexellis.io/docker-is-deleting-open-source-images/ but maybe as individual you might be fine. Hard to say at the moment

**Pull request merged**
