### PR TITLE
Added description for Girier JR-ZDS01 1 gang mini switch

### PR DESCRIPTION
**Pull request by schirin**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please also make a pr to add support for this device in https://github.com/koenkk/zigbee-herdsman-converters

**Comment by Koenkk** [comment]
Please resize the picture to 150x150 and move it to https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices

**Comment by schirin** [comment]
PLease check if picture update. Not sure if I did it correctly

**Comment by Koenkk** [comment]
It is not correct yet, please go to https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices , click add file and add the jpg and name it. `JR-ZDS01.jpg`

**Comment by schirin** [comment]
Sorry, stuck on how to upload pictures to master so created a new pull request with the correct image.

**Comment by Koenkk** [comment]
https://github.com/Koenkk/zigbee2mqtt.io/pull/983/files shows a lot of unexpected changes, I've added this picture in https://github.com/Koenkk/zigbee2mqtt.io/commit/8beea8513a9df66e960ed1a5efcf6e3cae0b5a84 , thanks!

**Pull request closed without merging**
