### PR TITLE
Add L&S Emotion Home Base

### PR DESCRIPTION
**Pull request by nordish1**

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also make a PR to add support for this device? (https://github.com/Koenkk/zigbee-herdsman-converters)

**Comment by nordish1** [comment]
Yes, but I'm on holiday till next week. Then I will make a PR.

**Comment by 87insane** [comment]
I also own an L&S Homebase. What exactly is missing here to integrate them?

**Comment by nordish1** [comment]
@87insane You can help with the PR @ [https://github.com/Koenkk/zigbee-herdsman-converters/pull/5908](url)

**Comment by 87insane** [comment]
404.. right Link?

**Comment by Koenkk** [comment]
Could you rename the picture to `A319463.jpg`?

**Comment by 87insane** [comment]
Hello everyone,

I've done a lot of testing and reading. The Home Base is also RGB capable and can also receive multiple end devices.
I myself have connected two cold and warm white devices to different masters.
If there is only one receiver, ls.js would work. But not as soon as several receivers are connected behind the home base.
Only circuit 1 is ever switched on or controlled. Circuit 2 doesn't work at all.

All devices behind the bridge are displayed individually via Deconz.

What is the best way to continue testing here?

PS: I adjusted the file:
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Emotion'],
    model: 'Emotion',
    vendor: 'L&S Deutschland GmbH',
    description: 'L&S Emotion Home Base',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device after pairing multiple devices and re-pairing the bridge?

**Comment by 87insane** [comment]
{"id":10,"type":"Router","ieeeAddr":"0xb43a31fffe773548","nwkAddr":23119,"manufId":4686,"manufName":"LS Deutschland GmbH","powerSource":"DC Source","modelId":"Emotion","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":"","zclVersion":3}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff0555de","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"","swBuildId":"1.0.0_r00000","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1688143220949,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Is this with 4 devices paired to it?

**Comment by 87insane** [comment]
No. I have paired 2 (CCT)

**Comment by nordish1** [comment]
> Could you rename the picture to `A319463.jpg`?

Done

**Comment by Koenkk** [comment]
Can you do the following:

- Force remove device through z2m frontend
- Restart z2m
- Pair the home base with 1 light bulb paired to it
- Provide the data/database.db entry here
- Now do the same but then pair 2 bulbs (so force remove, restart, pair 2 bulbs, and then data/database.db here)

**Comment by 87insane** [comment]
> Can you do the following:
> 
> * Force remove device through z2m frontend
> * Restart z2m
> * Pair the home base with 1 light bulb paired to it
> * Provide the data/database.db entry here
> * Now do the same but then pair 2 bulbs (so force remove, restart, pair 2 bulbs, and then data/database.db here)

Hey and good Morning,

1 Light Hint:
`{"id":10,"type":"Router","ieeeAddr":"0xb43a31fffe773548","nwkAddr":26551,"manufId":4686,"manufName":"LS Deutschland GmbH","powerSource":"DC Source","modelId":"Emotion","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Emotion","manufacturerName":"LS Deutschland GmbH","powerSource":4,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"","swBuildId":"1.0.0_r00000"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"","swBuildId":"1.0.0_r00000","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1688287164819,"defaultSendRequestWhen":"immediate"}
`
2 Light Hints:
`{"id":10,"type":"Router","ieeeAddr":"0xb43a31fffe773548","nwkAddr":26550,"manufId":4686,"manufName":"LS Deutschland GmbH","powerSource":"DC Source","modelId":"Emotion","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Emotion","manufacturerName":"LS Deutschland GmbH","powerSource":4,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"","swBuildId":"1.0.0_r00000"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":268,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"","swBuildId":"1.0.0_r00000","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1688287415965,"defaultSendRequestWhen":"immediate"}`

**Comment by Koenkk** [comment]
Please try with the following ext converter: https://gist.github.com/Koenkk/ed28269d960403a32b2d9b0054de1437

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by 87insane** [comment]
> Please try with the following ext converter: https://gist.github.com/Koenkk/ed28269d960403a32b2d9b0054de1437
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if issue is fixed

Hey @Koenkk,

if i save and activate this converter i cant see my other devices in zigbee2mqtt. In the DB they´re still there. I restarted the Service and see this in the Log:
`Zigbee2MQTT:error 05: Failed to call 'Bridge' 'start' (TypeError: e.light_onoff_brightness_colo
at /opt/zigbee2mqtt/data/extension/externally-loaded.js:23:22                                
at Array.map (<anonymous>)                                                                   
at Object.exposes (/opt/zigbee2mqtt/data/extension/externally-loaded.js:22:63)               
at Device.exposes (/opt/zigbee2mqtt/lib/model/device.ts:33:36)                               
at Bridge.getDefinitionPayload (/opt/zigbee2mqtt/lib/extension/bridge.ts:705:29)             
at /opt/zigbee2mqtt/lib/extension/bridge.ts:661:34                                           
at Array.map (<anonymous>)                                                                   
at Bridge.publishDevices (/opt/zigbee2mqtt/lib/extension/bridge.ts:620:47)                   
at Bridge.start (/opt/zigbee2mqtt/lib/extension/bridge.ts:109:20)                            
at processTicksAndRejections (node:internal/process/task_queues:96:5))`

i tried to find the typo but cant.

**Comment by Koenkk** [comment]
Did you copy the file correctly? `e.light_onoff_brightness_colo` should be `e.light_onoff_brightness_colortemp`

**Comment by Koenkk** [comment]
I made a mistake indeed, updated https://gist.github.com/Koenkk/ed28269d960403a32b2d9b0054de1437

**Comment by 87insane** [comment]
No Problem. For me its works. But i have no RGB LED. CCT ist okay for me. But i can see the Options for color. Is there a way to show the options only if the device supports the respective option? If i check a color (without to have a colored LED, i see an error message. "no converter avaliable for color".

**Comment by Koenkk** [comment]
Both things are currently hard to do, especially the separate devices so I propose to merge this as is for now.

**Comment by 87insane** [comment]
> 

OK.  I have separated the devices in fhem and can use them.  but can you possibly give some kind of indicator?  if multiple devices, then change topic path?  something like color_temp_l1/l2 is not so easy to handle.  for automatic creation of devices it would be good to have at least another path or at least something like device counters.

**Comment by Koenkk** [comment]
@87insane for this to work some changes to the z2m code base have to be made, I think this is good enough for now.

**Pull request merged**
