### PR TITLE
Update pairing_devices.md - adding note on interference

### PR DESCRIPTION
**Pull request by Daafip**
Addin information on interference: I didnt know about this, others should

### CODE REVIEW

**Comment by Koenkk** [comment]
I think we can link to the [FAQ](https://www.zigbee2mqtt.io/guide/faq/#why-does-my-device-not-or-fail-to-pair) from this page and add the note there

**Comment by Daafip** [comment]
Oh right makes more sense. Will you link that or should I add another pull request?

**Comment by Koenkk** [comment]
Please update this pr

**Comment by Daafip** [comment]
Updated pr: now links to FAQ

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
