### PR TITLE
Add CTP-R01

### PR DESCRIPTION
**Pull request by JJPro**
Aqara's new generation cube T1 Pro

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you make the background of the picture white?

**Comment by JJPro** [comment]
updated

**Comment by Koenkk** [comment]
Thanks, I'll merge this after https://github.com/Koenkk/zigbee-herdsman-converters/pull/5367 is merged.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
