### PR TITLE
Add info about power meter sum reset

### PR DESCRIPTION
**Pull request by mp3-10**
Added info about resetting power consumption sum (from TS011F_plug_1)

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you confirm that sending `zigbee2mqtt/FRIENDLY_NAME/set/factory_reset` with an empty payload also works?

**Comment by mp3-10** [comment]
Checked and:
`z2m: No converter available for 'factory_reset' ({})`

**Comment by Koenkk** [comment]
Whoops, had to be `reset`, not `factory_reset`

**Comment by mp3-10** [comment]
@Koenkk i tested: `zigbee2mqtt/FRIENDLY_NAME/set/reset` works too

**Comment by Koenkk** [comment]
Great, I'll add this later via expose. for now this is ok, thanks!

**Pull request merged**
