### PR TITLE
Adding documentation for Livolo dimmer and 2-gang switch. 

### PR DESCRIPTION
**Pull request by whitepail**
Hi,
  attaching pull request for livolo dimmer and 2-gang switch information in continuation to Koenkk/zigbee2mqtt#5516

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Piscator74** [comment]
I also have a Livolo 2-gang switch. I can get "state_left" and "state_right" fine, but I cannot set both end points with the described payloads in the [doc](https://www.zigbee2mqtt.io/devices/TI0001-switch-2gang.html).

When I use payload ```{"state_left": "ON"}``` or ```{"state_right": "ON"}```, I get the error:
```
Zigbee2MQTT:error 2021-04-03 00:56:21: Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: definition.endpoint is not a function
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:175:66)
    at Controller.callExtensionMethod (/app/lib/controller.js:380:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
```

When I use payload ```{"state": "ON"}```, it turns the left endpoint on (as it does for type 'TI0001-switch')
I tried finding the issue in the code, but could not so far. Any clues what I should be looking for?

I use the latest version: 1.18.1

**Comment by jeugen1** [comment]
I have exactly the same problem 
```
Zigbee2MQTT:error 2021-04-03 09:57:28: Failed to call 'EntityPublish' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Endpoint name 'left' is given but no endpoints defined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:233:25)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:52:44)
    at Controller.callExtensionMethod (/app/lib/controller.js:382:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
Zigbee2MQTT:error 2021-04-03 09:57:32: Failed to call 'EntityPublish' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Endpoint name 'right' is given but no endpoints defined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:233:25)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:52:44)
    at Controller.callExtensionMethod (/app/lib/controller.js:382:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
```

**Comment by Piscator74** [comment]
I have finally found a fix with a lucky 'guess'... The issue is that the endpoint definition is missing in ```TI0001-switch-2gang``` (file: **devices.js**) If you make that similar to what you see in ```TI0001          ```, it is fixed.

So add the following lines to ```TI0001-switch-2gang``` (file: **devices.js** and it works.
```
        endpoint: (device) => {
            return {'left': 6, 'right': 6};
        },
```

**Comment by jeugen1** [comment]
Thanks a lot!
As I use official z2m add-on to home assistant, I can't directly edit **devices.js**.
So I added external converter 
`external_converters:
  - livolo.js`
 where wrote the same code for TI001-swith-2gang:
'const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;
const livolo = require('zigbee-herdsman-converters/lib/livolo');

const device = {
        zigbeeModel: ['TI0001-switch-2gang'],
        model: 'TI0001-switch-2gang',
        description: 'Zigbee Switch 2 gang JS',
        vendor: 'Livolo',
        fromZigbee: [fz.livolo_new_switch_state_2gang],
        toZigbee: [tz.livolo_socket_switch_on_off],
        endpoint: (device) => {
            return {'left': 6, 'right': 6};
        },
        exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('right')],
        meta: {configureKey: 1},
        configure: livolo.poll,
        onEvent: async (type, data, device) => {
            if (type === 'stop') {
                clearInterval(globalStore.getValue(device, 'interval'));
                globalStore.clearValue(device, 'interval');
            }
            if (['start', 'deviceAnnounce'].includes(type)) {
                await livolo.poll(device);
                if (!globalStore.hasValue(device, 'interval')) {
                    const interval = setInterval(async () => {
                        await livolo.poll(device);
                    }, 300*1000); // Every 300 seconds
                    globalStore.putValue(device, 'interval', interval);
                }
            }
        },
};

module.exports = device;'
this makes the switch operational.

**Pull request merged**
