### PR TITLE
New Flex Products added

### PR DESCRIPTION
**Pull request by dhanukapulkit**

### CODE REVIEW

**Comment by Koenkk** [comment]
- Can you rebase your pr, it has a merge conflict currently
- I see a lot of unexpected changes, mainly files containing `MCC-5CG1487SFZ`

**Comment by Koenkk** [comment]
I still see some MCC files.

**Comment by dhanukapulkit** [comment]
@Koenkk  I checked and there was only one MCC file that i deleted. Can you please check?

**Comment by Koenkk** [comment]
@dhanukapulkit due to the new release all device pages have been generated causing all the conflicts. Can you create new a pr from a fresh branch?

**Comment by dhanukapulkit** [comment]
@Koenkk ok then i will close this pr and create a new one.

**Pull request closed without merging**
