### PR TITLE
Adding a new dimmable ledvance lamp

### PR DESCRIPTION
**Pull request by dhanukapulkit**
Adding a new dimmable ledvance lamp.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by dhanukapulkit** [comment]
Hi @Koenkk , Although this device is now supported, but i still see it as unsupported whenever i connect it with my Zgb coordinator. Will it be updated automatically? or what am i doing wrong here? Please support.

image

**Comment by Koenkk** [comment]
@dhanukapulkit it will appear as supported in z2m 1.27.2

**Comment by dhanukapulkit** [comment]
Thanks @Koenkk !
When is the general update for z2m carried out generally?
Is there a fixed schedule?

**Comment by Koenkk** [comment]
New release every 1st of the month

**Pull request merged**
