### PR TITLE
garage 

### PR DESCRIPTION
**Pull request by qianchen888**
submit garage picture

### CODE REVIEW

**Comment by Koenkk** [comment]
could you remove the jpg picture and make the png picture 512x512 with a transparent background?

**Comment by qianchen888** [comment]
> could you remove the jpg picture and make the png picture 512x512 with a transparent background?



> could you remove the jpg picture and make the png picture 512x512 with a transparent background?
yes

**Comment by Koenkk** [comment]
I don't see the changes being made yet, could you check it again?

**Comment by qianchen888** [comment]
> I don't see the changes being made yet, could you check it again?

I removed  the  jpg  picture and  submit  the  new  png picture 512x512 with a transparent background

**Pull request closed without merging**
