### PR TITLE
Added FUT035Z+

### PR DESCRIPTION
**Pull request by Luligu**
Added FUT035Z+ with image and markdown file.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you center the device on the image?

**Comment by Koenkk** [comment]
Thanks!

**Comment by Luligu** [comment]
Hi, done! 
It's nicer now :)
I had a doubt: is it ok the file name with + in it?
The pr takes so long... to finish

**Comment by Koenkk** [comment]
`+` are not a problem!

**Pull request merged**
