### PR TITLE
Add image + doc for Wiser motion sensor CCT595011 and additional note…

### PR DESCRIPTION
**Pull request by vaizki**
…s for Wiser dimmers WDE002334 and CCT5010-0001

### CODE REVIEW

**Comment by vaizki** [comment]
The Wiser motion sensor CCT595011 was added from another user's PR to herdsman-converters but as far as I could see the documentation and image have not been added here yet so maybe this could be merged?

P.S. not sure if we're supposed to branch off master or develop here..?

**Comment by vaizki** [comment]
Ah yes.. my original PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/3907 had:
```
zigbeeModel: ['CCT595011_AS'],
model: 'CCT595011',
```
This was based on CCT595011 being the code on the actual Schneider-Electric cardboard box and the sticker on the back of the sensor. The _AS is not included anywhere. But the PR that actually got merged was https://github.com/Koenkk/zigbee-herdsman-converters/pull/3948 with:
```
zigbeeModel: ['CCT595011_AS'],
model: 'CCT595011_AS',
```
so we are out of sync. Which one do we fix?

**Comment by vaizki** [comment]
Well I'm not using my own branch now since the device was included in dev branch via https://github.com/Koenkk/zigbee-herdsman-converters/pull/3948 .. but here is the entry in my DB:
```{
  "id": 15,
  "type": "EndDevice",
  "ieeeAddr": "0x804b50fffec855b1",
  "nwkAddr": 60935,
  "manufId": 4190,
  "manufName": "Schneider Electric",
  "powerSource": "Battery",
  "modelId": "CCT595011_AS",
  "epList": [
    1
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 1026,
      "inClusterList": [
        0,
        1,
        3,
        32,
        1024,
        1280,
        2821
      ],
      "outClusterList": [
        0,
        25
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "hwVersion": 0
          }
        },
        "ssIasZone": {
          "attributes": {
            "iasCieAddr": "0x00212effff07fc89",
            "zoneState": 1,
            "zoneStatus": 48,
            "numZoneSensitivityLevelsSupported": 3,
            "currentZoneSensitivityLevel": 0
          }
        },
        "genPollCtrl": {
          "attributes": {
            "checkinInterval": 14400
          }
        },
        "genPowerCfg": {
          "attributes": {
            "256": 0,
            "batteryPercentageRemaining": 200
          }
        },
        "msIlluminanceMeasurement": {
          "attributes": {
            "measuredValue": 16127
          }
        }
      },
      "binds": [
        {
          "cluster": 32,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00212effff07fc89",
          "endpointID": 1
        },
        {
          "cluster": 1,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00212effff07fc89",
          "endpointID": 1
        },
        {
          "cluster": 1280,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00212effff07fc89",
          "endpointID": 1
        },
        {
          "cluster": 1024,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00212effff07fc89",
          "endpointID": 1
        }
      ],
      "configuredReportings": [
        {
          "cluster": 1,
          "attrId": 33,
          "minRepIntval": 3600,
          "maxRepIntval": 62000,
          "repChange": 0
        },
        {
          "cluster": 1024,
          "attrId": 0,
          "minRepIntval": 15,
          "maxRepIntval": 3600,
          "repChange": 500
        }
      ],
      "meta": {}
    }
  },
  "appVersion": 1,
  "stackVersion": 6,
  "hwVersion": 0,
  "dateCode": "20201123",
  "swBuildId": "2011231",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": 1914004528
  },
  "lastSeen": 1648151844585,
  "defaultSendRequestWhen": "active"
}
```

**Comment by Koenkk** [comment]
@vaizki yours also ends with `_AS`, so `CCT595011_AS` is correct, could you rename the MD and JPEG to `CCT595011_AS.md/jpg`)

**Comment by vaizki** [comment]
As I mentioned, I am not using my own integration at this time because it would conflict with `dev` branch after the other PR was merged. If I was using my own, the model would be `CCT595011`.

I can rename the image and page for sure but for future reference, should `model:` be the same as `zigbeeModel:`? My understanding was that `model:` should reflect the manufacturer model number which in the case of this device does not include the `_AS` ending.

An image is worth a 1000 words:  https://imgur.com/a/5g8w4yK

**Comment by Koenkk** [comment]
>  My understanding was that model: should reflect the manufacturer model number which in the case of this device does not include the _AS ending.

You are right, updated the model in zigbee-herdsman-converters.

**Pull request merged**
