### PR TITLE
Added Schwaiger HAL300 E27 Light

### PR DESCRIPTION
**Pull request by marcr77**
I got a Schwaiger HAL300 E27 9,5W 806lm 1800-6500K + RGB
It describes itself as ZBT-RGBWLight-GLS0844

This is my first Change Request - I don't really know what to do - I hope it is correct

### CODE REVIEW

**Comment by marcr77** [comment]
I hope my request is correct this way

**Comment by Koenkk** [comment]
Hello, looks like this merge request should be made against https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js , please let me know if you can do this, otherwise I can add it myself.

**Comment by marcr77** [comment]
> Hello, looks like this merge request should be made against https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js , please let me know if you can do this, otherwise I can add it myself.

Hi,
I am not very firm in github things. Could you please add it. 
Best regards,
Marc

**Comment by Koenkk** [comment]
Added!

device will be supported in the 1 February release of z2m

**Pull request closed without merging**
