### PR TITLE
Added ZG-204ZL Luminance Motion Sensor

### PR DESCRIPTION
**Pull request by jaspernlp**
Documentation for the ZG-204ZL Luminance Motion Sensor

### CODE REVIEW

**Comment by Impact123** [comment]
You forgot the picture. I guess you could add the one from the [ZM-35H-Q](https://www.zigbee2mqtt.io/devices/ZM-35H-Q.html) since they look pretty much the same.

**Comment by jaspernlp** [comment]
Well spotted. I started with a copy of ZM-35H-Q. The intention was to use that image, but renamed the image name as well. Update has been made.

**Comment by Impact123** [comment]
I was thinking about uploading a picture with the same name as the device page because `docgen` would overwrite the picture's link.

**Comment by Koenkk** [comment]
Could you still add the picture to this pr?

**Comment by jaspernlp** [comment]
I have uploaded the image with the device name.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
