### PR TITLE
feat: add image for E8334RWMZB

### PR DESCRIPTION
**Pull request by buiducnhat**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please make the image 512x512

**Comment by buiducnhat** [comment]
> Please make the image 512x512

Thank you, I have done this!

**Comment by buiducnhat** [comment]
I see that it is existed [https://github.com/Koenkk/zigbee2mqtt.io/blob/master/public/images/devices/E8331SRY800ZB.png](https://github.com/Koenkk/zigbee2mqtt.io/blob/master/public/images/devices/E8331SRY800ZB.png).

Are there any problems?

**Comment by Koenkk** [comment]
Ah missed that, thanks!

**Pull request merged**
