### PR TITLE
new adapter added

### PR DESCRIPTION
**Pull request by gam-st**

### CODE REVIEW

**Comment by sergge1** [comment]
confirmed

**Comment by Koenkk** [comment]
I believe we don't have a stable FW for this device yet?

**Comment by gam-st** [comment]
> I believe we don't have a stable FW for this device yet?

Already have. Even more, the OTA fw update works on SLZB-06p10...

**Comment by Koenkk** [comment]
Where can I find the FW including the source? It should be added to https://github.com/Koenkk/Z-Stack-firmware

**Pull request closed without merging**
