### PR TITLE
Add: An Image for Aqara H1 Switch (WS-K01D)

### PR DESCRIPTION
**Pull request by LZXCorp**
This image is up to spec with transparent background and 512x512 sizing.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also make a pr to add support for this device to https://github.com/Koenkk/zigbee-herdsman-converters?

**Comment by LZXCorp** [comment]
Will be adding soon.

**Comment by TzeWey** [comment]
PR to support WS-K01D https://github.com/Koenkk/zigbee-herdsman-converters/pull/7282

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
