### PR TITLE
Update home_assistant.md for new bridge entities

### PR DESCRIPTION
**Pull request by mundschenk-at**
Adapts Home Assistant integration notes for new bridge entities

### CODE REVIEW

**Comment by waclaw66** [comment]
@mundschenk-at: Is there any particular reason why you've removed join timer with this PR? I'm configuring a new z2m instance and noticed that feature is missing now in the notes.

**Comment by mundschenk-at** [comment]
> @mundschenk-at: Is there any particular reason why you've removed join timer with this PR? I'm configuring a new z2m instance and noticed that feature is missing now in the notes.

Because a sensor entity for that is now automatically discovered on the bridge.

**Comment by waclaw66** [comment]
Timer was working fine before. Still don't understand why there is still `input_number.zigbee2mqtt_join_minutes` when the timer automation was removed.

**Comment by waclaw66** [comment]
> Not sure what you want here. You are free to use old the automation and and template entities if you want, they are just not necessary anymore because the bridge discovery now includes those features by default.
> 
That's I'm not sure, join with timer doesn't work anymore. If that was removed intentionaly, then ok, I can still use the old automation.

**Comment by mundschenk-at** [comment]
Yes, if you want custom discovery times you need to use the old automations. If there is a countdown, it will show up as a sensor value, but the HA switch entity toggles the state permanently (because it's easier to add fine-grained control via scripts/automations). 

There's been [some discussion](https://github.com/Koenkk/zigbee2mqtt/discussions/20468#discussioncomment-8005781) on having a second switch entity with the default timeout, but there didn't seem to be that much demand for that feature in the end, so it didn't get implemented (yet).

**Pull request merged**
