### PR TITLE
Added device image for innr FL 142 C

### PR DESCRIPTION
**Pull request by richardscholten73**
Added the image for innr FL 142 C "Color Flex LED strip 4m 2000lm"
PR for device:  https://github.com/Koenkk/zigbee-herdsman-converters/pull/6241

### CODE REVIEW

**Comment by richardscholten73** [comment]
> Could you provide a picture without the box on it?

Does it need to be jpg or can it be other formats like webp/png (with transparency)?

**Comment by Koenkk** [comment]
`.jpg` only

**Comment by richardscholten73** [comment]
> Could you provide a picture without the box on it?

Done.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
