### PR TITLE
Add information about the Paulmann 500.44 Dimmer

### PR DESCRIPTION
**Pull request by schwabe**
Also document the non-obvious reset procedure if I ever need to
do it again.

### CODE REVIEW

**Comment by Koenkk** [comment]
Is this device already supported? I don't see it in https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L3922 nor do I see an open PR.

**Comment by schwabe** [comment]
You merged the commit yesterday: https://github.com/Koenkk/zigbee-herdsman-converters/commit/5c4324624fe3dd68f64434ca6c49dbf46f0b01e9

**Comment by Koenkk** [comment]
Sorry missed that, in that case https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/50045.md has to be edited and no new file should be created (the name of that page will automatically be updated on the next zigbee2mqtt release, just add the pairing stuff for now there).

**Comment by schwabe** [comment]
How should file be called? Keep the 50045.md name or rename it to 50044_50045.md?

**Comment by Koenkk** [comment]
Nope, in this case just add a note and mention the device type.

**Comment by schwabe** [comment]
Like keep the two files but mention as a note that they share the device id with the other device?

**Comment by Koenkk** [comment]
Keeping the two files is not possible, as they have the same `zigbeeModel` (note that the documentation is generated so it is always consistent with: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js). I would recommend adding this to the notes of https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/50045.md#notes

**Pull request closed without merging**
