### PR TITLE
Update SRTS-A01.md: setting external temperature

### PR DESCRIPTION
**Pull request by yclybouw**
Explain how to set the external temperature measured by an external sensor.

See https://github.com/Koenkk/zigbee2mqtt/discussions/14291.

### CODE REVIEW

**Comment by Koenkk** [comment]
This part is automatically generated from [here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/xiaomi.ts#L3371C15-L3371C40), please update that instead, e.g.:

```
e.temperature_sensor_select(['internal', 'external']).withAccess(ea.ALL).withDescription('My custom text')
```

**Comment by yclybouw** [comment]
@Koenkk Would it make sense to expose this as a new field? I was thinking about:
```js
e.numeric('sensor_temp', access.SET).withUnit('°C')
.withDescription('Input for remote temperature sensor.'),
```

**Comment by Koenkk** [comment]
yes!

**Comment by yclybouw** [comment]
Closed in favour of https://github.com/Koenkk/zigbee-herdsman-converters/pull/6841

**Pull request closed without merging**
