### PR TITLE
Add Silicon Labs EFR32/EZSP flashing info and links

### PR DESCRIPTION
**Pull request by Hedda**
Add some basic information and links regarding how to flash Silabs EZSP based Zigbee adapters like EFR32.

@kirovilya @MattWestb @Loic691 can you have feedback/input on this EFR32/EZSP flashing info and links?

### CODE REVIEW

**Comment by Loic691** [comment]
what kind of information do you want ?

**Comment by Hedda** [comment]
> what kind of information do you want ?

For example method did you flash your Sonoff ZBDongle-E with?

**Comment by Hedda** [comment]
_Originally posted by @Koenkk in https://github.com/Koenkk/zigbee2mqtt/issues/13894#issuecomment-1241605940_

> Great, can you also make a pr for the docs with the link to the fw? Adding it to the description makes it too long.

@sujithg9 maybe can this flasing info maybe also be reused for docs Sonoff ZBDongle-E/Dongle-E with Zigbee Router firmware?

https://github.com/Koenkk/zigbee2mqtt/issues/13894

https://github.com/Koenkk/zigbee-herdsman-converters/pull/4641

**Comment by Hedda** [comment]
Not stale.

**Comment by Hedda** [comment]
Added URL link to the new "Universal Silicon Labs Flasher" by [puddly](https://github.com/puddly)

https://github.com/puddly/universal-silabs-flasher

FYI, that will soon ship with Home Assistant as part on their official [silabs-multiprotocol](https://github.com/home-assistant/addons/tree/master/silabs-multiprotocol) addon (based on [agners silabs flasher](https://github.com/agners/silabs-flasher))

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
