### PR TITLE
Update scenes.md

### PR DESCRIPTION
**Pull request by WhimsySpoon**
Details on how to create a scene with a transition were not immediately clear to me.

### CODE REVIEW

**Comment by Koenkk** [comment]
Good addition, thanks!

**Comment by WhimsySpoon** [comment]
Thanks, @Koenkk. Is my assumption correct that a transition cannot be supplied in `scene_store`? Because this would make things a lot easier, especially if we could add this to the front end.

**Comment by Koenkk** [comment]
It is, from the spec:

image

**Comment by WhimsySpoon** [comment]
Great! Is that honoured in z2m? So could I send:

```
{
    "scene_store": {
        "ID": 0,
        "name": "Scene Name",
        "transition": 5
    }
}
```

... and it would work? I'm sure I tried this in the past without any luck.

**Pull request merged**
