### PR TITLE
Create SolaxS10_zigbee.md

### PR DESCRIPTION
**Pull request by hieumaric**
Add new device SolaxS10_zigbee

### CODE REVIEW

**Comment by Koenkk** [comment]
This device is not supported by zigbee-herdsman-converters (https://github.com/Koenkk/zigbee-herdsman-converters) nor can I find any open PRs. Did I miss something?

**Comment by hieumaric** [comment]
hello!
I was trying to read how to support new devices in website zigbee2mqtt.io but it difficult to do
so i think easy way to do.. you can help me add my code to file devices.js of system to support my new devices ?
Now i doing in my pc and it action very good!

**Comment by Koenkk** [comment]
If you can share what you added to `devices.js` and provide an URL (link to product page) of the device I can add it.

**Comment by hieumaric** [comment]
this is  what i added to devices.js ( In attach)

[devices.txt](https://github.com/Koenkk/zigbee2mqtt.io/files/4846573/devices.txt)
Thank so much

**Comment by Koenkk** [comment]
And where can the device be bought?

**Comment by hieumaric** [comment]
This product was designed by me
i used E18-MS1PA1-IPX (CC2530) and image above just v1 version to try some function
version v2 being produced. I can send to your email?

**Comment by Koenkk** [comment]
For DiY devices it is required to provide a manual on how to create this device (otherwise support for this would be not beneficial for other users). The just released Zigbee2mqtt 1.14.1 now  supports external converters which allows to add support for devices without sharing it: https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration

**Pull request closed without merging**
