### PR TITLE
Add a new picture for ME168

### PR DESCRIPTION
**Pull request by dyx052612**
Add a new picture for ME168

### CODE REVIEW

**Comment by dyx052612** [comment]
Added a supported device picture

**Comment by dyx052612** [comment]
Because the appearance and models of these two products are different, two different pictures and introductions are required.

**Comment by Koenkk** [comment]
Can you improve the picture?

- Make the background fully white
- Increase size of the radiator

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
