### PR TITLE
Add documentation and device images for 5309330P6, 5309231P6, 5309031…

### PR DESCRIPTION
**Pull request by acaminiti**
…P9, 5309030P6, 5309031P6.

### CODE REVIEW

**Comment by acaminiti** [comment]
Documentation and devices images added for 5309330P6, 5309231P6, 5309031P9, 5309030P6, 5309031P6

**Comment by Koenkk** [comment]
If you want to have these being recognized as separate devices, you should add new definition for those (and not add them as additional zigbee model of an existing definition) (https://github.com/Koenkk/zigbee-herdsman-converters/commit/a8d2a73fd8f3b8ac9aa58a84dd20dda7b7a8d07f)

**Comment by acaminiti** [comment]
Is there a way then to add the other models into the documentation without splitting them in individual definitions??

**Comment by Koenkk** [comment]
@acaminiti no

**Pull request closed without merging**
