### PR TITLE
Update PTM_215Z.md

### PR DESCRIPTION
**Pull request by pow4all**
Added Feller push-botton (Switzerland) as white-label product

### CODE REVIEW

**Comment by Koenkk** [comment]
What is the model number of this device?

**Comment by pow4all** [comment]
Thanks for checking. Inside the Feller push-button the EnOcean PTM_215Z (GreenPower) module is used. So there is no specific model number (an order number is not really what we are looking for...).
If you search for "Feller" on zigbee2mqtt you will never find this information. That was my intention to add this information.

**Comment by pow4all** [comment]
https://online-katalog.feller.ch/kat_details.php?fnr=4120.2.S.FMI.61

**Comment by pow4all** [comment]
OK, I found a model number :)

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
