### PR TITLE
add image of EGLO 99099 remote

### PR DESCRIPTION
**Pull request by pswid**
As I see this device is added in the latest-dev release as **AwoX** device while it should as **EGLO**. It has EGLO logo visible at front and 99099 is EGLO P/N.

### CODE REVIEW

**Comment by Koenkk** [comment]
Added by @fsedarkalex in https://github.com/Koenkk/zigbee-herdsman-converters/pull/5853, @fsedarkalex can you confirm this is an EGLO device?

**Comment by fsedarkalex** [comment]
Yes: https://github.com/Koenkk/zigbee2mqtt/issues/16890

**Comment by fsedarkalex** [comment]
Sorry, I did not know better how to fill the fields.

**Comment by Koenkk** [comment]
Moved it!

**Pull request merged**
