### PR TITLE
Create TS0505B.jpg

### PR DESCRIPTION
**Pull request by jgorissen**

### CODE REVIEW

**Comment by Koenkk** [comment]
There is no device with model `TS0505B` currently supported, can you give some more context why you added this picture?

**Comment by jgorissen** [comment]
I added it because I have that Tuya device in 30 watt, 50 watt and 100 watt. And they are all recognized without any issue. But I get the zigbee logo in the Z2M overview.
The model column points to https://www.zigbee2mqtt.io/devices/TS0505B.html#tuya-ts0505b

**Comment by Koenkk** [comment]
Are you using an external converter? (check your z2m configuration.yaml)

**Comment by jgorissen** [comment]
No, the file is like this:
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.200
  user: *******
  password: *******
serial:
  port: /dev/zigbeesticky
frontend:
  port: 8080
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x001788010b3767a0':
    friendly_name: Hue plafond 1
  '0xa4c1385858d2e938':
    friendly_name: Flood 1
    homeassistant: {}
    legacy: false
    optimistic: true
    qos: 1
.......
.......

Here is the log when it is joining:
Info 2023-09-06 22:24:19Device '0xa4c13879acbdab32' joined
Info 2023-09-06 22:24:19MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c13879acbdab32","ieee_address":"0xa4c13879acbdab32"},"type":"device_joined"}'
Info 2023-09-06 22:24:19Starting interview of '0xa4c13879acbdab32'
Info 2023-09-06 22:24:19MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c13879acbdab32","ieee_address":"0xa4c13879acbdab32","status":"started"},"type":"device_interview"}'
Info 2023-09-06 22:24:19MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c13879acbdab32","ieee_address":"0xa4c13879acbdab32"},"type":"device_announce"}'
Info 2023-09-06 22:24:20Successfully interviewed '0xa4c13879acbdab32', device has successfully been paired
Info 2023-09-06 22:24:20Device '0xa4c13879acbdab32' is supported, identified as: TuYa Zigbee RGB+CCT light (TS0505B)
Info 2023-09-06 22:24:20MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee RGB+CCT light","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":153},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500}],"property":"color_temp","type":"numeric","unit":"mired","value_max":500,"value_min":153},{"access":7,"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":3,"description":"Do not disturb mode, when enabled this function will keep the light OFF after a power outage","name":"do_not_disturb","property":"do_not_disturb","type":"binary","value_off":false,"value_on":true},{"access":3,"description":"Power on behavior state","name":"color_power_on_behavior","property":"color_power_on_behavior","type":"enum","values":["initial","previous","cutomized"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0505B","options":[{"access":2,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).","name":"transition","property":"transition","type":"numeric","value_min":0},{"access":2,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).","name":"color_sync","property":"color_sync","type":"binary","value_off":false,"value_on":true},{"access":2,"description":"State actions will also be published as 'action' when true (default false).","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0xa4c13879acbdab32","ieee_address":"0xa4c13879acbdab32","status":"successful","supported":true},"type":"device_interview"}'
Info 2023-09-06 22:24:20Configuring '0xa4c13879acbdab32'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/light/0xa4c13879acbdab32/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0xa4c13879acbdab32/set","device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":500,"min_mireds":153,"name":"0xa4c13879acbdab32","schema":"json","state_topic":"zigbee2mqtt/0xa4c13879acbdab32","supported_color_modes":["xy","color_temp"],"unique_id":"0xa4c13879acbdab32_light_zigbee2mqtt"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/select/0xa4c13879acbdab32/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0xa4c13879acbdab32/set/effect","device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"enabled_by_default":false,"icon":"mdi:palette","name":"0xa4c13879acbdab32 effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0xa4c13879acbdab32_effect_zigbee2mqtt"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/switch/0xa4c13879acbdab32/switch_do_not_disturb/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0xa4c13879acbdab32/set/do_not_disturb","device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"name":"0xa4c13879acbdab32 do_not_disturb","payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/0xa4c13879acbdab32","unique_id":"0xa4c13879acbdab32_switch_do_not_disturb_zigbee2mqtt","value_template":"{% if value_json.do_not_disturb %} true {% else %} false {% endif %}"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/sensor/0xa4c13879acbdab32/color_power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:palette","name":"0xa4c13879acbdab32 color power on behavior","state_topic":"zigbee2mqtt/0xa4c13879acbdab32","unique_id":"0xa4c13879acbdab32_color_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.color_power_on_behavior }}"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/select/0xa4c13879acbdab32/color_power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0xa4c13879acbdab32/set/color_power_on_behavior","device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"entity_category":"config","icon":"mdi:palette","name":"0xa4c13879acbdab32 color power on behavior","options":["initial","previous","cutomized"],"state_topic":"zigbee2mqtt/0xa4c13879acbdab32","unique_id":"0xa4c13879acbdab32_color_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.color_power_on_behavior }}"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'homeassistant/sensor/0xa4c13879acbdab32/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c13879acbdab32"],"manufacturer":"TuYa","model":"Zigbee RGB+CCT light (TS0505B)","name":"0xa4c13879acbdab32","sw_version":"z.1.0"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0xa4c13879acbdab32 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0xa4c13879acbdab32","unique_id":"0xa4c13879acbdab32_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2023-09-06 22:24:20MQTT publish: topic 'zigbee2mqtt/0xa4c13879acbdab32', payload '{"color_mode":"xy","color_power_on_behavior":null,"do_not_disturb":null,"linkquality":102,"state":null}'
Info 2023-09-06 22:24:20MQTT publish: topic 'zigbee2mqtt/0xa4c13879acbdab32', payload '{"color_mode":"xy","color_power_on_behavior":null,"do_not_disturb":null,"linkquality":102,"state":null}'
Info 2023-09-06 22:24:20Successfully configured '0xa4c13879acbdab32'

**Comment by Koenkk** [comment]
can you provide a screenshot of the z2m frontend, device, about page?

**Comment by jgorissen** [comment]
image

**Comment by Koenkk** [comment]
what z2m version are you using?

**Comment by jgorissen** [comment]
Zigbee2MQTT:info  2023-09-08 19:18:17: Starting Zigbee2MQTT version 1.30.3 (commit #24c6b2e)
Zigbee2MQTT:info  2023-09-08 19:18:17: Starting zigbee-herdsman (0.14.103)
Zigbee2MQTT:info  2023-09-08 19:18:17: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-09-08 19:18:17: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'

**Comment by Koenkk** [comment]
Updating to the latest z2m version (1.33.0) should fix it.

**Comment by jgorissen** [comment]
What does it fix? I only wanted to add an image for the floodlight. Does it have it? If so, why does https://www.zigbee2mqtt.io/devices/TS0505B.html#tuya-ts0505b not show it?
Or does it get another device name suddenly?

**Comment by Koenkk** [comment]
The model will be slightly different and thus it will have an image.

**Pull request closed without merging**
