### PR TITLE
[docs] Update MCCGQ01LM pairing steps

### PR DESCRIPTION
**Pull request by fatmcgav**
I was having issues getting the `MCCGQ01LM` devices paired. 
Reset would get the 3 blinks followed by a few more blinks, however the device would just timeout after 10 seconds with:
`Cannot get the Node Descriptor of the Device: 0x****** (Error: Timed out after 10000 ms)`

These steps worked for me :)

### CODE REVIEW

**Comment by Koenkk** [comment]
This was indeed the pairing procedure before zigbee2mqtt 1.7.0, but with zigbee2mqtt 1.7.0 this is not needed anymore.

**Comment by fatmcgav** [comment]
Ahh, ok... Is `1.7.0` available? Or any way I can test with the latest changes to confirm they work?

**Comment by Koenkk** [comment]
Yes it has been released on sunday

**Comment by fatmcgav** [comment]
> Yes it has been released on sunday

Cool, I'll upgrade and give it a go... 😀

**Pull request closed without merging**
