### PR TITLE
add support for ML-ST-BP-DIM

### PR DESCRIPTION
**Pull request by gid204**
I deleted the 'Effects' paragraph from the markup file as this device doesn't support it, even though it says "Do not edit below this line" on line 28. Please let me know if I am meant to do this another way.

### CODE REVIEW

**Comment by Koenkk** [comment]
I will check the effect part, can you convert the image to a 150x150 jpg?

**Comment by gid204** [comment]
@Koenkk sorry about that, png has been converted to jpg.

**Comment by gid204** [comment]
fixed the typo causing the auto checks to fail.

**Comment by gid204** [comment]
transparency removed from the image (white background inserted).

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
