### PR TITLE
Added Merten MEG5113-0300/MEG5165-0000

### PR DESCRIPTION
**Pull request by 7h0mas-R**
Pairing needs some explanation since it is not documented with the component.
Also setting of the timer value is currently not yet supported - needs some explanation

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by phil239** [comment]
Hi there! Thanks so much for your great work! With this project I could finally get rid of my Wiser Home Touch and simultaneously integrate our Wiser shutters into HomeKit. So awesome, I really appreciate! 
One last annoying problem: Was anyone able to find out and successfully implement the Zigbee command for setting the timer? I would really like to be able to set an exact position of the shutters….

**Comment by 7h0mas-R** [comment]
Hi Phil,
Since you seem to have a Home Touch, you could try to find out, how commands are sent by the Home Touch. That would make it easier than trying to guess how it is done, especially, if they use non-standard functions.
Instructions on [how to sniff traffic can be found here](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531). I can't, because I do not have a Home Touch.
If that information is available, it could be implemented.

**Comment by phil239** [comment]
Unfortunately I sold the Home Touch a week ago. 

Anyone else here having one?

**Comment by phil239** [comment]
Hi everyone,
the guys from the deconz project seem to have made “little” progress on this device.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5773

Anyone able to implement these improvements in z2m?

Thanks!

**Pull request merged**
