### PR TITLE
Add picture for new Tuya button _TZ3000_mrpevh8p

### PR DESCRIPTION
**Pull request by Chartreusito**
Add picture for _TZ3000_mrpevh8p

### CODE REVIEW

**Comment by Koenkk** [comment]
`_TZ3000_mrpevh8p` is not supported in zigbee-herdsman-converters yet, can you make a PR for it?

**Comment by Chartreusito** [comment]
Sure, it's in the pipe ! I'll link it here when it's done.

**Comment by Chartreusito** [comment]
PR for zigbee-herdman-converters : https://github.com/Koenkk/zigbee-herdsman-converters/pull/6225

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
