### PR TITLE
Add table of known ZGP routers

### PR DESCRIPTION
**Pull request by burmistrzak**
This table by far doesn't include all ZGP-capable routers, only the ones that have been confirmed. 😅

Related: https://github.com/Koenkk/zigbee2mqtt/issues/23031

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by chris-1243** [comment]
@burmistrzak What kind of info should I check, while sniffing traffic, in order to add routers in your table ? As you already know, I do not use Philips Hue as ZGP router in my network. I would like to share the device used but I wish to be sure those are acting correctly.

**Comment by chris-1243** [comment]
One more question:

If the ZGP device is already paired to a router, I guess there is a way to check if the packets are sent as `unicast`

**Comment by chris-1243** [comment]
@burmistrzak  Here are the results of my tries. All done with a PTM215Z

[ZGP router table.txt](https://github.com/user-attachments/files/15903134/ZGP.router.table.txt)

**Comment by chris-1243** [comment]
@burmistrzak There is a firmware update form some Hue devices (1.116.5) which seems to fix the issue.

How would you like to show this to the users ? e.g. [9290022166](https://www.zigbee2mqtt.io/devices/9290022166.html#philips-9290022166) is working as `unicast` firmware 1.116.5 but as `broadcast` firmware 1.116.3...

**Pull request merged**
