### PR TITLE
Add device support for: Philips Hue Being Pendant 915005914601

### PR DESCRIPTION
**Pull request by GizzGool**
This Philips model can also be discovered with the reference 915005914601

Tested using external converter:

```
const {Definition} = require('zigbee-herdsman-converters/lib/types');
const ota = require('zigbee-herdsman-converters/lib/ota');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const {philipsOnOff, philipsLight, philipsFz, philipsTz} = require('zigbee-herdsman-converters/lib/philips');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['915005914601'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '915005914601', // Vendor model number, look on the device for a model number
    vendor: 'Philips', // Vendor of the device (only used for documentation and startup logging)
    description: 'Hue Being Pendant', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    //fromZigbee: [], // We will add this later
    //toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

### CODE REVIEW

**Comment by Koenkk** [comment]
- Could you also submit a PR for the device itself?
- Can you add the pictures? (150x150 jpg with white background)

**Comment by GizzGool** [comment]
Hello Koenkk,

I'm sorry if I'm not very comfortable with the method for adding devices. I normally put in zigbee2mqtt.io/public/images/devices a 915005914601.jpg file but maybe not submitted it? I have tried something else ?

Also, how to create a PR (Pull Request ?) for the device itself?

Have a good day :-)

**Comment by Koenkk** [comment]
For the device, click the pencil icon here and add it: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/philips.ts

**Comment by GizzGool** [comment]
Thank you very much for your help in trying to make progress with Github  😃
I hope I followed your request by adding the piece of code in philips.ts.
In any case, I now carefully keep the procedure to follow because I admit that in the tutorial, it is really too light for me and I would have needed to really have a step to step given my limited skills 😇
Again thanks to you and for all your work. 👍
I did a little sponsorship for you for Christmas 🎅🎄

**Comment by Koenkk** [comment]
Thanks, happy Christmas!

**Pull request merged**
