### PR TITLE
Update bulb images

### PR DESCRIPTION
**Pull request by giosad**
Update 2 bulbs images:
- [IKEA LED1935C3](https://www.zigbee2mqtt.io/devices/LED1935C3.html) / [Product link](https://www.ikea.com/es/en/p/tradfri-led-bulb-e14-250-lumen-wireless-dimmable-warm-white-chandelier-clear-30441380/)
- [TuYa TS0505B](https://www.zigbee2mqtt.io/devices/TS0505B.html) /  [Product link](https://www.aliexpress.com/item/1005002760795498.html)

### CODE REVIEW

**Comment by Koenkk** [comment]
The TS0505B should be kept as is, I have this device and it looks exactly like this.

Could you provide your data/database.db entry of this device so I could identify it differently?

**Comment by giosad** [comment]
Here it is:


{"id":2,"type":"Router","ieeeAddr":"0xa4c138306edc75fa","nwkAddr":28193,"manufId":4417,"manufName":"_TZ3210_remypqqm","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_remypqqm","powerSource":1,"zclVersion":3,"appVersion":94,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"startUpColorTemperature":454}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c083e1","endpointID":242},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c083e1","endpointID":242}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":94,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1642238825752,"useImplicitCheckin":true}

**Comment by Koenkk** [comment]
Seems this device has quite some manufacturer names attached to it (https://github.com/Koenkk/zigbee-herdsman-converters/blob/462431dbb26ae92d98acb634b739118998834609/devices/tuya.js#L160). I think it would be better to edit the picture to show both the controller + bulb.

**Comment by giosad** [comment]
Any example or a general guidance? This is what I did:
image

**Comment by Koenkk** [comment]
yes looks good, no need to squash, I can do that when merging

**Comment by giosad** [comment]
Fixed (also added the explanation to the commit) and rebased over the latest master.

**Comment by Koenkk** [comment]
perfect!

**Pull request merged**
