### PR TITLE
Add Dresden Electronic Kobold dimmer information

### PR DESCRIPTION
**Pull request by drott**
Add link to device info in markdown file, as well as add an image.

### CODE REVIEW

**Comment by Koenkk** [comment]
The images are already there (https://github.com/Koenkk/zigbee2mqtt.io/blob/master/public/images/devices/BN-600110.jpg). Can you rebase this pr?

**Comment by Koenkk** [comment]
Thanks!

**Comment by drott** [comment]
> The images are already there (https://github.com/Koenkk/zigbee2mqtt.io/blob/master/public/images/devices/BN-600110.jpg). Can you rebase this pr?

Done, I noticed when I got the conflict that these were already added after #1500  in 583fc738115b1f9afcca5a9807a6816ca91b8b2c. Rebased.

**Comment by drott** [comment]
Thanks for the quick merge.

**Pull request merged**
