### PR TITLE
Update W2049.md

### PR DESCRIPTION
**Pull request by MattWestb**
The name of the type is **not** production year and week.
The real name shall being used and not YYWW.

The name is [E2001 (stainless)](https://fccid.io/FHO-E2001) and [E2002 (white)](https://fccid.io/FHO-E2002).

### CODE REVIEW

**Comment by MattWestb** [comment]
CSA certificate: https://zigbeealliance.org/zigbee_products/styrbar-remote-control/

**Comment by Koenkk** [comment]
Thanks!

**Comment by MattWestb** [comment]
Sorry i see i have missing one E  in the last E2001/E2002.

But i think its easier you is fixing it then the index file also need being renamed that is still W2049 in the device list  :-((

**Comment by Koenkk** [comment]
@MattWestb I see it's already correct in zigbee-herdsman-converters, so these docs will be updated with the next release. (tomorrow)

**Pull request merged**
