### PR TITLE
Fix links to herdsman source in 01_support_new_devices.md

### PR DESCRIPTION
**Pull request by samthor**
Some of these links didn't work as herdsman's repo has been rearranged to add the src/ folder. Fix links.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by jfcabral** [comment]
Thanks @samthor.

@Koenkk, I've noticed that the docs still haven't been updated to reflect this change:
image

**Comment by Koenkk** [comment]
@jfcabral what links are not correct? Everything seems to look good on my side.

**Comment by jfcabral** [comment]
> @jfcabral what links are not correct? Everything seems to look good on my side.

All seems good now 😄 

Thank you @Koenkk 👍 
imagem

**Pull request merged**
