### PR TITLE
Added ED-10042 light picture and info

### PR DESCRIPTION
**Pull request by dbloom86**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please also create a pr for https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by dbloom86** [comment]
> Please also create a pr for https://github.com/Koenkk/zigbee-herdsman-converters

Hi Koen,

Do you have like a manual for these things? I'm not really familiar with GitHub, only with how to use what someone else makes. Not with cloning, changing, merging, pushing and pulling.
However I did create an externa converter for this type of light, and it works, so it would be a waste if someone else had to create it as well.

Maybe you can explain how those things work?

**Comment by Koenkk** [comment]
Cloning is not necessary, click the edit (pencil) icon in the right top of the file here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/ecodim.js

**Comment by dbloom86** [comment]
Ok I just did. Hopefully it;s the right way. It's working for me, so should work for other people as well.
However, this doesnt make the readme file and picture for the device does it?

**Comment by Koenkk** [comment]
Created the pr, could you give me the data/database.db entry of this device?

https://github.com/Koenkk/zigbee-herdsman-converters/pull/3607/files

**Comment by dbloom86** [comment]
Sure. I believe it's this part:

{"id":7,"type":"Router","ieeeAddr":"0xb4e3f9fffe3578e8","nwkAddr":50288,"manufId":4098,"manufName":"_TZ3210_yluvwhjc","powerSource":"Mains (single phase)","modelId":"TS0501B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0501B","manufacturerName":"_TZ3210_yluvwhjc","powerSource":1,"zclVersion":3,"appVersion":89,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":89,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1641190302292,"useImplicitCheckin":true}

However, I have 2 of these devices, and they show different entries in de database.db file. But the above part is from the one I created the external converter for. 

Also do I need to approve the change as well?

**Comment by Koenkk** [comment]
Thanks, added!

**Pull request merged**
