### PR TITLE
Add Note section to 3A / NUE HGZB-DLC4-N12B

### PR DESCRIPTION
**Pull request by Yuke-hd**
I have this light and was able to reset it with a hue dimmer switch

### CODE REVIEW

**Comment by Yuke-hd** [comment]
I wasn't able to test the other 4 ways, but as per the [product description ](https://www.amazon.com.au/ZigBee-Downlight-Compatible-Bridge-Automation/dp/B09VSD95PB) 3A/Nue lights are Hue compatible, should we also add the other reset methods?

**Comment by Koenkk** [comment]
Can it also be reset with an ON/OFF sequence? (e.g. 5x ON/OFF)?

**Comment by Yuke-hd** [comment]
> Can it also be reset with an ON/OFF sequence? (e.g. 5x ON/OFF)?

is there a detailed guide?

**Comment by Koenkk** [comment]
Similar to e.g. https://www.youtube.com/watch?v=npxOrPxVfe0

**Comment by Yuke-hd** [comment]
> Similar to e.g. https://www.youtube.com/watch?v=npxOrPxVfe0

Yep it can

**Comment by Yuke-hd** [comment]
Updated the README

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
