### PR TITLE
Replace Hive SLB2 image with correct one - old was ikea repeater

### PR DESCRIPTION
**Pull request by robertalexa**
Hi Koen,

Just a simple fix. The image used for Hive SLB2 was in fact an Ikea Repeater. I have replaced it with the correct one, using Blakadder as the source of the asset.

Thanks,
Rob

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, can you resize the image to 150x150? (required for all images)

**Comment by robertalexa** [comment]
> Thanks, can you resize the image to 150x150? (required for all images)

Done. Sorry, I have not thought to check the sizes, my bad.

**Comment by Koenkk** [comment]
Thanks!

**Comment by robertalexa** [comment]
> Thanks!

You are welcome. It is weird that the test failed again, despite the image being 150x150

**Comment by Koenkk** [comment]
@robertalexa this is another image, will fix it later.

**Comment by robertalexa** [comment]
> @robertalexa this is another image, will fix it later.

Oh if only i read the message properly.

I will push another PR for that image to save you some time

**Pull request merged**
