### PR TITLE
Add documentation for kubernetes/helm

### PR DESCRIPTION
**Pull request by jlpedrosa**
Companion PR for the helm chart. https://github.com/Koenkk/zigbee2mqtt/pull/21852

Adds alternative method of installation `Kubernetes`

### CODE REVIEW

**Comment by jlpedrosa** [comment]
@Koenkk  I would not merge this until we have generated successfully a release and tested everything e2e (index.yaml from release, tar is actually working)

**Comment by Koenkk** [comment]
Will hold it then, btw changed the subdomain to `charts` (from `chart) since that is more common

**Comment by Koenkk** [comment]
@jlpedrosa closed by accident?

**Comment by jlpedrosa** [comment]
:facepalm: absolutely by accident, I was cleaning my forks, let me re push it, I have it locally.

**Comment by jlpedrosa** [comment]
GH kept the repository Id, so I can't re open it. I created a new PR. sorry for the inconvenience.

**Pull request closed without merging**
