### PR TITLE
feat: Added reference and support for Philips 3402931P7

### PR DESCRIPTION
**Pull request by mmornati**
## What?

Added the reference and support for the Philips Hue Adore Bathroom Mirror Light (3402931P7). Some information, to check what I'm delivering can be found [here](https://zigbee.blakadder.com/Philips_3402931P7.html). (NB I'm not able to find the information on the Philips Website anymore... maybe the lamp is not sold anymore).

A PR for the global support is also provided on the zigbee-herdsman-converters website https://github.com/Koenkk/zigbee-herdsman-converters/pull/4564

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you please change the file extension of the picture to `.jpg` instead of `.jpeg`?

**Comment by mmornati** [comment]
Hey sorry... I didn't even noticed that the extension was put tu jpeg 😅
Will change it as soon as I'm on a PC.

The quality of the image is not that much... But 150 pixel for a big light in too low 😉

**Comment by mmornati** [comment]
Done!

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
