### PR TITLE
Update E2202.md

### PR DESCRIPTION
**Pull request by nocin**
Added Battery Type and Pairing instructions

### CODE REVIEW

**Comment by kkarczmarczyk** [comment]
duplicate of https://github.com/Koenkk/zigbee2mqtt.io/pull/2672

**Comment by Koenkk** [comment]
The battery type is not included in https://github.com/Koenkk/zigbee2mqtt.io/pull/2672, please rebase the PR.

**Comment by nocin** [comment]
Hi @Koenkk,

I'm not very experienced with Git and GitHub, but isn't it possible to select "Rebase and merge" when merging?
Or is there a way to do this via the Github web interface? Then I would need a hint on how to do this. Thanks!

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
