### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by freitas3001**
PLUG-EDP-SOLAR.png : >> PLUG-EDP-REDY-SOLAR.png
- Device type: Router
- Zigbee Model: ZB-SmartSolarPlug-1.1.1
- Zigbee Manufacturer: EDP-WITHUS
- Description: re:dy plug
- Firmware build date: 20150602
- Manufacturer: EDP
- Model: Smart Solar Plug

PLUG-EDP-REDY.png:
- Device type: Router
- Zigbee Model: ZB-SmartPlug-1.0.0
- Zigbee Manufacturer: EDP-WITHUS
- Description: re:dy plug
- Firmware build date: 20131021
- Manufacturer: EDP
- Model: PLUG EDP RE:DY

PLUG-EDP-RE-DY.png >> PLUG-EDP-REDY-IR:
- Device type: Router
- Zigbee Model: ZB-SmartPlugIR-1.0.0
- Zigbee Manufacturer: EDP-WITHUS
- Description: re:dy plug
- Firmware build date: 20150515
- Manufacturer: EDP -Model: PLUG EDP RE:DY

### CODE REVIEW

**Comment by freitas3001** [comment]
PLUG-EDP-REDY-SOLAR

PLUG-EDP-SOLAR-energy

**Comment by Koenkk** [comment]
Could you also make a PR to add support for these devices [here](https://github.com/Koenkk/zigbee-herdsman-converters)?

**Comment by freitas3001** [comment]
> Could you also make a PR to add support for these devices [here](https://github.com/Koenkk/zigbee-herdsman-converters)?

I've tried, but I can't understand how to do it!

**Comment by Koenkk** [comment]
Are you already using an external converter for these devices? if yes, please post it here

**Pull request closed without merging**
