### PR TITLE
Adding picture for Heimgard Technologies HT-INS-2

### PR DESCRIPTION
**Pull request by Zterio**

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you convert the picture to a `.jpg` with white background?

**Comment by Zterio** [comment]
Done, Image has been converted as requested.

**Comment by Zterio** [comment]
Also adding in device image for Schneider Electric Wiser Power Micromodule CCTFR6730

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
