### PR TITLE
Schneider Electric MEG5126-0300/MEG5171-0000 and MEG5116-0300/MEG5171-0000

### PR DESCRIPTION
**Pull request by Nailik**
- added support for Schneider Electric MEG5126-0300/MEG5171-0000
- added switch_action and indicator_mode support to MEG5116-0300/MEG5171-0000

updated docs for https://github.com/Koenkk/zigbee-herdsman-converters/pull/7050

### CODE REVIEW

**Comment by Koenkk** [comment]
Please make the picture `.png` with transparent background

**Comment by Nailik** [comment]
> Please make the picture `.png` with transparent background

should the .jpg removed then or is it used as "backup" ?

**Comment by Koenkk** [comment]
The `docs/images/MEG5116-0300.jpeg` can be removed.

**Comment by Nailik** [comment]
finished it up!

**Comment by Koenkk** [comment]
Can you delete `docs/images/MEG5116-0300.jpeg` from this pr?

**Comment by Nailik** [comment]
pretty sure you meant `docs/images/MEG5126-0300.jpeg` - i removed it

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
