### PR TITLE
add image for new Wisdom DMZ250 dimmer module

### PR DESCRIPTION
**Pull request by SjonHortensius**

### CODE REVIEW

**Comment by SjonHortensius** [comment]
how can I link the device to this specific device-image, does it require me to add some additional metadata somewhere?

**Comment by Koenkk** [comment]
This is fine, can you rename the picture to `DMS250.jpg`?

**Comment by SjonHortensius** [comment]
yes, done

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
