### PR TITLE
LED Indication info for Philips Hue Motion Sensor

### PR DESCRIPTION
**Pull request by uncle-fed**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by uncle-fed** [comment]
I am not sure if the same applies / works for the other Hue motion sensor (outside). 
I don't have that device.
https://www.zigbee2mqtt.io/devices/9290019758.html

**Comment by Koenkk** [comment]
It does (I have this device). Docs will be automatically updated with this on the next release.

**Comment by uncle-fed** [comment]
Does this mean that my change will be automatically copied to the other device?
Because I only modified one page, not both.

**Comment by Koenkk** [comment]
Yes (these docs are generated so your text will slightly change)

**Pull request merged**
