### PR TITLE
Add Doc for Legrand 067776A Shutter SW with with level control

### PR DESCRIPTION
**Pull request by apages2**

### CODE REVIEW

**Comment by apages2** [comment]
#[https://github.com/Koenkk/zigbee-herdsman-converters/pull/6227](url)

**Review by apages2 — COMMENTED** [review]
update notes

**Comment by FabianMangold** [comment]
Cross ref. to https://github.com/Koenkk/zigbee-herdsman-converters/pull/6256

**Comment by FabianMangold** [comment]
Hi @Koenkk,
Could you merge this one following the addition of the switch ([PR#6256](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6256))
Thanks a lot

**Comment by Koenkk** [comment]
Thanks for pining me!

**Pull request merged**
