### PR TITLE
Add Hive SLR1 image

### PR DESCRIPTION
**Pull request by robertalexa**
This PR is in preparation of another PR in zigbee-herdsman-converters in order to support the SLR1 Hive receiver. The PR is not ready yet and won't be for at least a week due to logistics between myself and the person that asked for support.

The support issue can be found here:
https://github.com/Koenkk/zigbee2mqtt/issues/8184

I have also gitignores the .idea folder that gets created by IntelliJ IDEA (IDEs) - in my case PhpStorm. I hope that is ok with you Koen

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, will merge this once it is merged in zigbee -herdsman converters.

**Comment by robertalexa** [comment]
@Koenkk can this be merged pls? It is required by today's release :)

**Comment by Koenkk** [comment]
I've already added the pictures (didn't see this pr before the release), can you rebase this PR?

**Comment by robertalexa** [comment]
@Koenkk 

I have pulled upstream master into mine and merged my master into my branch. Then made sure the images were the correct ones and pushed the manual merge.

I hope that is correct

**Comment by Koenkk** [comment]
perfect!

**Pull request merged**
